### ISSUE TITLE
vte291: Transparency slider always active

### ISSUE THREAD

**Issue by egmontkob** [mate-desktop/mate-terminal#102]
Profile settings -> Background

The transparency slider is always sensitive, even when "Solid" is selected. I'm not sure if it used to be / supposed to be this way, or if it should only be active if transparent mode is selected.

I might have broken it by my patches to issue 66, sorry in that case :P

**Comment by raveit65** [comment]
fixed by
https://github.com/mate-desktop/mate-terminal/commit/5ecc6d7c26e7d721245bc06ba0d699d7f072c052
