### ISSUE TITLE
GTK3 :Built-in schemes names doubled

### ISSUE THREAD

**Issue by egmontkob** [mate-desktop/mate-terminal#103]
Profile preferences -> Colors -> Built-in schemes

The dropdown has all the entries name duplicated, that is:
Black on white Black on white
Gray on black Gray on black
etc. etc.

**Comment by raveit65** [comment]
Ok, seems not a issue with vte port.
I see this issue with using old gtk3 version compiled with vte290 too.

**Comment by raveit65** [comment]
well, imo the responsable code for this is somewhere between line https://github.com/mate-desktop/mate-terminal/blob/master/src/profile-editor.c#L332
and
https://github.com/mate-desktop/mate-terminal/blob/master/src/profile-editor.c#L562
I guess it's in init_color_scheme_menu (GtkWidget *combo_box)
This was changed in gtk3 port commit https://github.com/mate-desktop/mate-terminal/commit/9537fb9c0567157ca181c106c9c79756cee541bd
But i see nothing which cause the load of double names in GtkCombobox.
I compared the code with g-t code too, but beside from using gsettings to read/set the schemas i see no big differents.
Maybe this is the result of missing port of GtkColors to GdkRGBA.

**Comment by egmontkob** [comment]
Once they're added from profile-preferences.ui, notice the "child" tag around line 1400 (not sure if the preceding "model4" line is relevant). This is not present in gnome-terminal.

And then once they're added in profile-editor.c L569 pack_start() and set_attributes().

Remove whichever of the two doesn't break the gtk2 version :D 

Also note that profile-editor.c L558 is misleadingly not indented under the "for" loop.

(line number according to the vte291 branch)

**Comment by raveit65** [comment]
He, good finder.
I will disable L569 pack_start() and set_attributes() from profile-editor.c because it doesn't affect gtk2 version.
Removing the child section from UI file removes the the entries from gtk2 version here.
thanks again

**Comment by raveit65** [comment]
fixed https://github.com/mate-desktop/mate-terminal/commit/1e8eef25c7fa7ce17cd978ccc246fbfd40eb38f6
