### ISSUE TITLE
(gtk3) remove utmp

### ISSUE THREAD

**Issue by egmontkob** [mate-desktop/mate-terminal#104]
vte-0.38 removed utmp/wtmp support: https://bugzilla.gnome.org/show_bug.cgi?id=747046

mate-terminal should also remove the corresponding config option and its UI checkbox if gtk3 is being used. Or, alternatively, add utmp support itself, using libutempter.
##

**Comment by raveit65** [comment]
Well, i'm missing links in vte upstream report that listed applications (ie. pam_weel) have dropped umtp support.
So, this could be a prob in rare cases on distros which aren't use newest software versions.
On the  other hand i don't think that those distros will use a gtk3 compiled mate-terminal soon.
So it seems that adding a config option for gtk3 build might be a sufficient solution.
@flexiondotorg @monsta @clefebvre 
What do you think?

**Comment by raveit65** [comment]
@egmontkob 
maybe my eyes are old....but where is the UI checkbox? :)

**Comment by egmontkob** [comment]
Profile preferences -> Title and command -> Update login records...

**Comment by egmontkob** [comment]
> Well, i'm missing links in vte upstream report that listed applications (ie. pam_weel) have dropped umtp support.

I don't think any app has dropped it. (For pam_wheel in particular, there's a config option not to rely on utmp, and relying on utmp for a security-sensitive tool is a no-brainer anyways.)

What you see in that bugreport is all there is to this story.

**Comment by monsta** [comment]
Hmm the bug report says it's about 0.39, not 0.38...

Anyway, I don't know what this thing does, so I can't really vote +1 or -1 here. :smile:
If that stuff is indeed as useless and insecure as it's stated in the upstream report, then I guess it's ok to remove the support for it...

**Comment by raveit65** [comment]
https://git.gnome.org/browse/gnome-terminal/commit/?id=d3aa520b96dd0e4ceb66b45a517df9d23ad10845
Hmm, this change a UI file too.
Means we can't do that until we support gtk2.

**Comment by egmontkob** [comment]
FYI: mate-terminal is gtk3-only now, requiring a pretty recent vte, so the given checkbox never works.

**Comment by raveit65** [comment]
Why is this line removed at /src/terminal-screen.c from https://git.gnome.org/browse/gnome-terminal/commit/?id=d3aa520b96dd0e4ceb66b45a517df9d23ad10845
```
-  if (!g_settings_get_boolean (profile, TERMINAL_PROFILE_LOGIN_SHELL_KEY))
-    pty_flags |= VTE_PTY_NO_LASTLOG;
```

**Comment by egmontkob** [comment]
None of the `VTE_PTY_NO_*` values are used anymore, their doc says "Unused. Deprecated: 0.38". They were mistakenly not removed from from VTE, possibly along with the corresponding `pty_flags` parameter to the `vte_terminal_spawn_async()` and similar functions. Removing them will break the API, so we're waiting with it until we need to break the API anyway ([see here](https://bugzilla.gnome.org/show_bug.cgi?id=762043)).

vteapp and gnome-terminal now pass  `VTE_PTY_DEFAULT` a.k.a. 0 here.

**Comment by raveit65** [comment]
Ok, i dropped that line too in PR.
