### ISSUE TITLE
Build failure with version 1.13.0

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-terminal#107]
Got this error on gtk3 build:

terminal-window.c:3429:38: error: ‘VTE_TERMINAL_WRITE_DEFAULT’ undeclared (first use in this function)

Somehow triggered by the changes in configure.ac. Double tested by dropping the new configure.ac into the Wayland supporting version immediately after building it sucessfully, then reconfiguring and rebuilding. Got the exact same error

**Comment by monsta** [comment]
WTF... how did it compile before? There's no ```vte_terminal_write_contents``` in GTK+3 version of VTE, there's ```vte_terminal_write_contents_sync``` instead...

**Comment by monsta** [comment]
Aaaahhh.... 

```
#if 1
/*
 * We don't want to enable content saving until vte supports it async.
 * So we disable this code for stable versions.
 */
#include "terminal-version.h"

#if (TERMINAL_MINOR_VERSION & 1) != 0
#define ENABLE_SAVE
#else
#undef ENABLE_SAVE
#endif
#endif
```

Now we bumped mate-terminal version to 1.13.0, so ```ENABLE_SAVE``` is defined and the piece of code in question gets compiled :smile:

**Comment by monsta** [comment]
There, https://github.com/mate-desktop/mate-terminal/pull/108 should fix it.

**Comment by lukefromdc** [comment]
Just build this with gtk3, it works

**Comment by monsta** [comment]
Good, fix merged.
