### ISSUE TITLE
Gtk+-3.20: terminal starts always as a small window

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-terminal#111]
There are 2 relevant bugreport at gnome bugzilla about.
https://bugzilla.gnome.org/show_bug.cgi?id=760944
https://bugzilla.gnome.org/show_bug.cgi?id=757282
And the issue seems related to 
https://git.gnome.org/browse/gtk%2B/commit/?id=08974a1e9a6099a5a94b9d56970dbf96e473ba87
And the fix for gnome-terminal does not help.
https://git.gnome.org/browse/gnome-terminal/commit/?id=28d8f12e5024e7278d747f573da671cf97293a69

**Comment by raveit65** [comment]
Btw. using a fixed size, ie 640x360 helps.

**Comment by raveit65** [comment]
As workaround i set a min height/width in all our themes.
https://github.com/mate-desktop/mate-themes/commit/4b7682c346b06fa877128dfc3a68ec07a567f1bb

**Comment by lukefromdc** [comment]
I just tested https://github.com/XRevan86/mate-terminal and it worked fine for me with gtk3.19.11 even after I removed the theming workaround code from my GTK theme.
