### ISSUE TITLE
Please add in provides package "xterm"

### ISSUE THREAD

**Issue by torvn77** [mate-desktop/mate-terminal#114]
Translate: I wanted to replace the terminal "xterm" more convenient "mate-terminal" for which I was trying to uninstall this package, but the attempt of removal has resulted in the apt tried to put "gnome-trminal". Forced to remove the package using dpkg blocked the installation of updates and programs the requirement to supply the missing packet back. Make please so that I can use "mate-termina"l as the main terminal.
Original: Я хотел заменить терминал "xterm" на более удобный "mate-terminal" для чего пытался удалить этот пакет, но попытка удаления приводила к тому, что апт пытался вместо него поставить "gnome-trminal". Принудительное же удаление пакета с помощью dpkg блокировало установку обновлений и программ требованием поставить недостающий пакет обратно. В общем сделайте пожалуйста так, чтобы я мог использовать "mate-termina"l как основной терминал системы.

**Comment by monsta** [comment]
Это не к нам :smile:
Это сюда: https://bugs.debian.org/src:mate-terminal
