### ISSUE TITLE
Please support italic escape code

### ISSUE THREAD

**Issue by mixmastamyk** [mate-desktop/mate-terminal#115]
The code for italics is:  ` \e[3m`

See:

http://superuser.com/questions/204743/terminal-that-supports-the-ansi-italic-escape-code

for terminals that support it.

**Comment by monsta** [comment]
This will be auto-implemented when mate-terminal becomes GTK+3 only as it will use GTK+3 version of VTE where it's already [implemented](https://git.gnome.org/browse/vte/commit/?id=ad68297cb8792c5f2927ccac44014507ff310da2).

**Comment by monsta** [comment]
As mate-terminal is finally GTK+3 only, this feature will work now. You'll be able to try it once MATE 1.16 is released.
