### ISSUE TITLE
Can't resize F24 terminal via Menu

### ISSUE THREAD

**Issue by rflribeiro** [mate-desktop/mate-terminal#122]
Can't resize terminal using Alt+T+1...4.
![screenshot at 2016-06-29 12-45-18](https://cloud.githubusercontent.com/assets/91149/16460368/63b70e36-3dfd-11e6-9c16-68de0b2fa4a0.png)

Version 1.12.1-1.fc23 - http://koji.fedoraproject.org/koji/buildinfo?buildID=703368 works fine.

**Comment by raveit65** [comment]
I think it is a bug with vte291-0.44 because gnome-terminal have the same problem.
See https://github.com/mate-desktop/mate-terminal/issues/123#issuecomment-231381567

**Comment by monsta** [comment]
Yes, these menu items do nothing here as well. Debian Testing with GTK+ 3.20.6 and VTE 0.44.2.

**Comment by monsta** [comment]
I think we should close this since it works now.

**Comment by rflribeiro** [comment]
Excellent work! It is working perfectly!
