### ISSUE TITLE
reverse search is broken with vte291-0.44.2-1.fc24

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-terminal#123]
Reverse search works well with current master if i use it in f23 with vte291-0.42.x.
Of course gtk+ versions are also different but i don't think that it is gtk+ related.
@egmontkob 
I there any change in vte291-0.44 which can cause this issue.
I noticed that the reverse search works well with gnome-terminal in f24.

**Comment by raveit65** [comment]
Btw. also changing the terminal size is broken with f24 but not in f23,
so maybe there are more changes in vte.
@egmontkob ???

**Comment by monsta** [comment]
Yes, I've noticed that in Debian Testing as well, vte2.91 is 0.44.2.

**Comment by raveit65** [comment]
Update: i notice that gnome-terminal have exaxtly the same issues.
- no reverse search
- changing the terminal size via menu is broken

**Comment by raveit65** [comment]
Maybe the resize issue is related to deprecated https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-resize-to-geometry

**Comment by egmontkob** [comment]
This could easily be relevant, dunno: https://bugzilla.gnome.org/show_bug.cgi?id=765328

**Comment by raveit65** [comment]
Thx, i asked for clarification there.

**Comment by raveit65** [comment]
I could bisect vte and found the culprit, see https://bugzilla.gnome.org/show_bug.cgi?id=769400

**Comment by monsta** [comment]
"merry christmas" :laughing:

**Comment by monsta** [comment]
Alright, so fix is in 0.44 and 0.46 branches upstream (not to mention the master one of course). Should we close this, or wait until the distros get the patch? I've already submitted the patch to Ubuntu at https://bugs.launchpad.net/bugs/1627007.

**Comment by raveit65** [comment]
closing
