### ISSUE TITLE
mate-terminal manual is missing description of the "-x" option

### ISSUE THREAD

**Issue by epgfm** [mate-desktop/mate-terminal#126]
In the "Terminal options" category, only "-e" flag has documentation.
Correct me if I'm wrong, "-x" differs from "-e" where subsequent arguments need not be quoted.
Is this because "-x" is deprecated and shouldn't be used?

**Comment by monsta** [comment]
I looked at manpage of gnome-terminal in Debian (for some reason it's not provided upstream) and at the code too... so they still have the "-x" option, just like we do, and it's mentioned in the manpage. I think it won't hurt to add it to our manpage as well.

**Comment by monsta** [comment]
>  Correct me if I'm wrong, "-x" differs from "-e" where subsequent arguments need not be quoted.

Indeed, this seems to be the only difference.

**Comment by monsta** [comment]
Done, entry added to the manpage.
