### ISSUE TITLE
Option to highlight all the occurrences of a term that is being searched for.

### ISSUE THREAD

**Issue by negora** [mate-desktop/mate-terminal#127]
In the dialog window to search for a term, it would be convenient to have an option to highlight, optionally, all the occurrences of that term. I'm referring the dialog window that is opened when clicking in the "Search -> Find..." menu.

The result of this functionality could look like the one of the Pluma text editor. Although, in that case, all the occurrences are highlighted by default, and there is no option to disable it before the search, only after it.

Other terminal emulators, such as Konsole, already have this function. It's very useful when you're reading logs and want to search for certain lines, but don't want to filter out the rest. Also when you're reading the manual of a command and want to know in which sections a certain option is mentioned.

Thank you.

**Comment by monsta** [comment]
Konsole is written in Qt, so better example would be some GTK+ terminal, like roxterm, terminator, gnome-terminal, xfce4-terminal, lxterminal.

**Comment by negora** [comment]
Thanks for your answer, Monsta.

I mentioned Konsole because it's the only terminal emulator, of which I'm aware, that has that function. I tried other GTK terminal emulators in the past:

	Gnome Terminal
	MATE Terminal
	xfce4-terminal
	Terminator

But none of them allowed to highlight all the occurrences. I didn't know ROXTerm. But I've just tested it, and I haven't been able to highlight the matches either.

It's one of that "simple" features that you believe not to need, until you use it for first time. Indeed, I worked with XFCE for years and I never "missed" it. But after working with it in Konsole for several years, I think that it's really useful. It helps not to lose the orientation in long texts, in contrast to what happens when you jump from word to word manually. It gives you a global view of the occurrences and where they're located.

**Comment by monsta** [comment]
It might turn out it's not implemented in VTE, a terminal widget library that all mentioned GTK+ terminals use.

@egmontkob: can you please give a hint about it?

**Comment by negora** [comment]
I've found a bug report in Launchpad, referred to Terminator, in which someone says that VTE only allows to highlight one occurrence at a time. Check the comment #13 here: https://bugs.launchpad.net/ubuntu/+source/terminator/+bug/271487 . So you're right. It seems to be a VTE limitation. 

Maybe should I open a feature request in the VTE project instead? That way, every project using VTE would benefit from it.

**Comment by negora** [comment]
I've found out that there is already a feature request in Gnome's Bugzilla: https://bugzilla.gnome.org/show_bug.cgi?id=627886 . It's not one specific for this feature, but one that mentions several ways to improve the VTE's search function. And highlighting all the results is one of them.

I don't know if the will implement this feature. Meanwhile, I believe that I'm going to start using "less +R", instead of "tail -f", to read log files. That way I'll be able to use the search function of the "less" command, which effectively highlights all the results. It's not the same, but for certain usages like mine, it may be a good replacement.

Thanks for mentioning VTE, monsta. That led me into the right direction ;) .

**Comment by monsta** [comment]
Sure, no problem. I'll close this report then since it's VTE-specific.
