### ISSUE TITLE
mate-terminal interprets the mouse wheel events to up/down instead of scrolling up/down in a screen

### ISSUE THREAD

**Issue by samuel-phan** [mate-desktop/mate-terminal#128]
OS: Linux Mint 18 (Ubuntu 16.04) MATE desktop environment
`mate-terminal` version `1.14.0-1+sarah`

The mouse wheel scrolls up/down in the mate-terminal output buffer correctly, but when I'm in a `screen`, it doesn't anymore, and scrolls through the shell command history instead, as if I press on up/down.

This bug seems to have been detected some time ago, with gnome-terminal, and an option has been added in the menu "Profile Preferences" --> Tab "Scrolling" and with an option "Use keystrokes to scroll on alternate screen".

When I open a 2nd screen console (`Ctrl-a` `Ctrl-c`), the mouse wheel behaves normally (it scrolls up/down the output buffer) until I press enter (no command) or run a command.

Bug in Ubuntu Lucid:
https://bugs.launchpad.net/ubuntu/+source/screen/+bug/106995

It used to work fine with Linux Mint 17.3 with `mate-terminal` `1.12.0-1+rosa`.

**Comment by monsta** [comment]
It's in a terminal widget library, not in a terminal app. Please report in on LP against ```vte``` source package.
