### ISSUE TITLE
Add option to disable blinking cursor

### ISSUE THREAD

**Issue by asdfjkl** [mate-desktop/mate-terminal#130]
A blinking cursor is incredible annyoing for those of us who work a lot with the terminal.

The option to disable the blinking cursor was at some stage removed from gnome(2) terminal preferences dialog, because... well because the gnome developers were just retarded (and by that, I mean they can do _anything_).

Please add this option to mate-terminal again. I know there is a global option to disable the blinking cursor in all application, but there is a huge difference between a tiny cursor in a wordprocessor or when typing in a browser URL, and that big chunk in the terminal.

I was also unable to disable the blinking cursor with gsettings or gconftool2 for mate terminal; I could not find the setting anywhere...

Pretty please ... for some of us, blinking cursors in terminals are a kind of chinese water torture ( http://www.jurta.org/en/prog/noblink )...

**Comment by raveit65** [comment]
Do you know in which version of gnome-terminal this was removed?
Btw. Mate use gsettings, not mateconf or gconf.

**Comment by asdfjkl** [comment]
It seems they removed it approx. at 2.21.90, cf. the bug report here https://bugzilla.gnome.org/show_bug.cgi?id=342921
and never added it back.

I tried
a) gsettings list-recursively org.mate.terminal
but couldn't find a suitable value.

b) also by browsing with dconf-editor (not mateconf) I was unable to find a setting...

**Comment by raveit65** [comment]
I found the option for it, you can set via profile preferences GUI for you profile.
In general tap there is a drop down menu called ' blinking of cursors' or so.
With 3 options, use system settings, never and always.

**Comment by egmontkob** [comment]
> because the gnome developers were just retarded

Or maybe they just had different opinion than yours. Maybe that there should only be one global cursor blinking preference for the entire GNOME desktop and not one for each app. ;)

> and that big chunk in the terminal

Just FYI: You can set I-Beam cursor, I wonder if you've tried that. I do recommend it.

**Comment by asdfjkl** [comment]
@raveit65 Thanks! It's indeed there, dunno how I missed it - MATE is awesome!
@egmontko I have no problem if other folks have different opinions and preferences, but they _took_ _away_ the ability to chose my preference for no reasons at all. Also my preference is not to have a different blinking for _each_ app, really just for the terminal due to the very different cursor.
