### ISSUE TITLE
mouse scroll to switch tabs not working (1.14.0)

### ISSUE THREAD

**Issue by noone3** [mate-desktop/mate-terminal#133]
I recently upgraded Arch Linux from mate-terminal-1.12.1-1-x86_64 to mate-terminal-gtk3-1.14.0-1-x86_64 (in connection with upgrading the other mate packages to 1.14 gtk3 versions).
This seems to have broken the ability to switch between tabs (of terminal sessions) with the mousewheel when the mousepointer hovers over the tab bar.
Mouse wheel scrolling inside a terminal window to get history does still work fine.
I tried to configure this vie the keyboard shortcuts but it seems mouse buttons can't be used there?
This is a nice usability feature, can it be added again?
It worked fine up to version 1.12.1.

**Comment by monsta** [comment]
Mouse scrolling had been removed from GtkNotebook in GTK+3: https://bugzilla.gnome.org/630226 :confused:

**Comment by egmontkob** [comment]
... and there's a gnome-terminal commit linked from that bug that reverts this.

**Comment by noone3** [comment]
Many thanks for the pointers, I was able to build a patched version of mate-terminal-gtk3 locally and the scrolling works fine!
Could this patch be added so it works by default in future versions?
The patch I used is attached, please note I've taken out the #if statements as I just did a quick test with the gtk3 package version.
I'm not sure if there is a common code base for gtk2+gtk3, if yes the conditions need to be re-added.
[mate-terminal-1.14-tabscroll.patch.txt](https://github.com/mate-desktop/mate-terminal/files/418019/mate-terminal-1.14-tabscroll.patch.txt)

**Comment by raveit65** [comment]
@noone3 can you do a pull request for master please?
I will cherry-pick this to 1.14 branch, as it is a bug fix.

**Comment by raveit65** [comment]
Btw. master is gtk3 only, so no version checks are needed.

**Comment by noone3** [comment]
Ok I just did a pull request against master (without the version checks).
If they are necessary due to gtk2/gtk3 code, please let me know and I'll add them again.

**Comment by monsta** [comment]
Thanks guys, I'll check the PR. Yes, version checks are not needed as mate-terminal is GTK+3 only now in master (and so it will be in 1.16 release).

**Comment by monsta** [comment]
Ok, PR works fine here, thanks.

@egmontkob: should we also pick this one?
https://git.gnome.org/browse/gnome-terminal/commit/?id=70965e71db7d1c2fac0237988344972b564c46b5
combined with
https://git.gnome.org/browse/gnome-terminal/commit/?id=35a509165750d0ecefe9f26702d0f3c0e230f0c2

**Comment by monsta** [comment]
Fix merged in https://github.com/mate-desktop/mate-terminal/commit/8d2eb0898154f2624e2ae34039169f307a3411a5, handling of ```GDK_SCROLL_SMOOTH``` added in https://github.com/mate-desktop/mate-terminal/commit/622e2d1272bf2d7a99d147482ae6a51b0a77f188.
