### ISSUE TITLE
mate-terminal ignores Select-by-word characters with VTE 0.38

### ISSUE THREAD

**Issue by RajKiranS** [mate-desktop/mate-terminal#136]
After upgrading mate from v1.12.1-1 to v1.14.0-1, 'Select-by-word' characters is being ignored. Our distro is RHEL7.2. I am able to reproduce this issue easily.

Example: Here is my 'Select-by-word' characters: A-Za-z0-9_

Expected output in v1.12.1-1:
![expected-1-12-1](https://cloud.githubusercontent.com/assets/1935195/18125542/61ccd380-6f94-11e6-9360-2089f98ae766.PNG)

Issue in v1.14.1-1:
![issue--14-2](https://cloud.githubusercontent.com/assets/1935195/18125527/4c075f66-6f94-11e6-882f-d38cd82e984b.PNG)

Is this a known issue? Could you please help out here.

Thanks,
Raj
##

**Comment by raveit65** [comment]
Hmm, confirmed with f24 beta and mate-terminal-1.15.1-1.fc24.x86_64. At least 1.14.x in from epel repo or f23 are patched versions which are similar, Here we switched to gtk3 and vte2.91, what will be 1.16. in near future.
I guess it's a regression by vte291. Can you please try out gnome-terminal which use also vte-291 ?

**Comment by RajKiranS** [comment]
Yes, I tried out on gnome-terminal v2.14.3 which is based on vte291 and this also IGNORES 'select-by-word' characters.

foo@bar: ~ $ gnome-terminal --version
GNOME Terminal 3.14.3

foo@bar: ~ $ rpm -qa | ag -i vte291
vte291-0.38.3-2.el7.x86_64

foo@bar: ~ $ dconf read /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/word-char-exceptions
@ms 'A-Za-z0-9_'

Output: IGNORES 'select-by-word' characters.

Is there any workaround?

**Comment by raveit65** [comment]
Sadly not that i know, it is all vte291 related.

**Comment by egmontkob** [comment]
vte-0.38 does not support word characters at all (the API is missing, so it's not that it silently ignores the setting), so there's nothing mate-terminal could do here.

Both older (e.g. 0.36) and newer (e.g. 0.40) versions of vte do support this feature.

**Comment by RajKiranS** [comment]
Thanks for the updates. Can we soon expect mate-terminal with vte-040 build to resolve other vte291 issues?

**Comment by raveit65** [comment]
> Can we soon expect mate-terminal with vte-040 build to resolve other vte291 issues?

This is only fixable by vte itself, not sure if rehad will ever update vte in rhel7. Try to file ot a report against vte in rhel7.
Closing this as we can't do nothing.
