### ISSUE TITLE
mate-terminal: crashes on profile changes

### ISSUE THREAD

**Issue by norbusan** [mate-desktop/mate-terminal#137]
[gdb.txt](https://github.com/mate-desktop/mate-terminal/files/447221/gdb.txt)
Dear all,

I am running Debian/sid with mate-terminal 1.14.1, and I see consistent crashes when changing the profile via "Terminal -> Change Profile -> <name>". This is 100% reproducible by me, and the Debian maintainer has confirmed this behavior on Debian.

I have also caught a core dump/backtrace, attached.

The respective Debian bug is https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836188

Let me know if I can provide further information

Thanks, Norbert

**Comment by jamen** [comment]
I'm having this error too, on Arch Linux.  

Receiving it through right click context menu: Profiles > Profile Preferences > crash

**Comment by denis-dordoigne** [comment]
Same issue for me (Debian/sid with mate-terminal 1.14.1), segfault while changing profile and all mate-terminal windows closed. For yout information, there are these warnings while starting mate-terminal (from xterm) : 

(mate-terminal:8149): GLib-GIO-WARNING **: Failed to parse translated string 'Terminal' for key 'title' in schema 'org.mate.terminal.profile': 0-1:unknown keyword

(mate-terminal:8149): GLib-GIO-WARNING **: Using untranslated default instead.

(mate-terminal:8149): GLib-GIO-WARNING **: Failed to parse translated string '[UTF-8,current,ISO-8859-15,ISO-8859-1]' for key 'active-encodings' in schema 'org.mate.terminal.global': 1-2:unknown keyword

(mate-terminal:8149): GLib-GIO-WARNING **: Using untranslated default instead.

(mate-terminal:8149): Gtk-WARNING **: TerminalWindow 0x561b4c9cc310 is drawn without a current allocation. This should not happen.

(mate-terminal:8149): Gtk-WARNING **: GtkBox 0x561b4cb32150 is drawn without a current allocation. This should not happen.

(mate-terminal:8149): Gtk-WARNING **: GtkVScrollbar 0x561b4cd86290 is drawn without a current allocation. This should not happen.

(mate-terminal:8149): Gtk-WARNING **: GtkMenuBar 0x561b4cba31c0 is drawn without a current allocation. This should not happen.

(mate-terminal:8149): Gtk-WARNING **: GtkImageMenuItem 0x561b4cc7a2a0 is drawn without a current allocation. This should not happen.

(mate-terminal:8149): Gtk-WARNING **: GtkAccelLabel 0x561b4cc793a0 is drawn without a current allocation. This should not happen.

(mate-terminal:8149): Gtk-WARNING **: GtkImageMenuItem 0x561b4cc7d360 is drawn without a current allocation. This should not happen.

(mate-terminal:8149): Gtk-WARNING **: GtkAccelLabel 0x561b4cc7cb70 is drawn without a current allocation. This should not happen.

(mate-terminal:8149): Gtk-WARNING **: GtkImageMenuItem 0x561b4cc81450 is drawn without a current allocation. This should not happen.

(mate-terminal:8149): Gtk-WARNING **: GtkAccelLabel 0x561b4cc7fd50 is drawn without a current allocation. This should not happen.

(mate-terminal:8149): Gtk-WARNING **: GtkImageMenuItem 0x561b4cc81b90 is drawn without a current allocation. This should not happen.

(mate-terminal:8149): Gtk-WARNING **: GtkAccelLabel 0x561b4cc82ba0 is drawn without a current allocation. This should not happen.

(mate-terminal:8149): Gtk-WARNING **: GtkImageMenuItem 0x561b4cc83460 is drawn without a current allocation. This should not happen.

(mate-terminal:8149): Gtk-WARNING **: GtkAccelLabel 0x561b4cc845d0 is drawn without a current allocation. This should not happen.

(mate-terminal:8149): Gtk-WARNING **: GtkImageMenuItem 0x561b4cc92290 is drawn without a current allocation. This should not happen.

(mate-terminal:8149): Gtk-WARNING **: GtkAccelLabel 0x561b4cc91ba0 is drawn without a current allocation. This should not happen.

(mate-terminal:8149): Gtk-WARNING **: GtkVScrollbar 0x561b4cd86290 is drawn without a current allocation. This should not happen.


Thanks,

-- 
Denis Dordoigne

**Comment by jamen** [comment]
Reinstalled from source here off Git, and it seems to work.  👍

**Comment by monsta** [comment]
Yes, this should be fixed in 1.16 which has better support for GTK+ 3.20 and 3.22.
