### ISSUE TITLE
After 'Relaunch' (alt+r) window size is smaller.

### ISSUE THREAD

**Issue by kopias** [mate-desktop/mate-terminal#138]
Tested on Ubuntu Mate 16.04 x64

Steps to reproduce:
1. Open Terminal (alt+ctrl+t)
2. Exit (ctrl+d)
3. Relaunch (alt+r)

the height of window is smaller by the info header (exit status and relaunch button) height

if you do this (step 2 and 3) enough times you will see what i mean

btw. thx for this great terminal
##

**Comment by monsta** [comment]
I presume you're using some additional app launcher? Because Alt-R doesn't do anything for me.

**Comment by kopias** [comment]
first thx for taking a look at this.
im using atom text editor addon to launch python script in console, but its not required to see this issue
if you run terminal and either type 'exit' or do ctr+d you get the relaunch info header
![2](https://cloud.githubusercontent.com/assets/3462746/20249697/3907a416-a9ff-11e6-8782-201f47d23e80.png)
if you relaunch and exit a couple of times you can clearly see the size of a window is shirked
![3](https://cloud.githubusercontent.com/assets/3462746/20249708/6bc60c58-a9ff-11e6-9c21-ff64534f8ff9.png)

**Comment by raveit65** [comment]
> if you run terminal and either type 'exit' or do ctr+d you get the relaunch info header

Nope, normal behaviour is that those commands closes the terminal.

**Comment by kopias** [comment]
In Profile options on "Title and Command" tab you need to have "When command exits:" set to "Hold the terminal open"

ugh sorry again i have this option change so long ago i forgot about it

**Comment by raveit65** [comment]
> In Profile options on "Title and Command" tab you need to have "When command exits:" set to "Hold the terminal open"

Hey, nice hidden feature....new for me :-)
But i can't reproduce this with fedora 24/25 with mate-terminal-1.16.0/1 or fedora 23 with m-t-1.14.1.
Here playing arround with crtl+d and alt+r does not reduce the terminal size.
Which version are you using currently?
16-04 sounds like 1.14.x.
@flexiondotorg 
Can you reproduce the issue.

**Comment by kopias** [comment]
on ubuntu mate 16.04 is using version 1.12.1 of mate-terminal

I have tried mate-terminal 1.16.0 on xubuntu 16.10 and the issue is gone

i think we can safely close this issue

p.s. this 'relunch' feature is very handy since it will relaunch any command that is invoked with for example: 
`mate-terminal -e "python /path/to/some/file.py"`

**Comment by monsta** [comment]
> In Profile options on "Title and Command" tab you need to have "When command exits:" set to "Hold the terminal open"

Oh... this is one of these features I've never tried :smile:
