### ISSUE TITLE
Terminal produces blank window

### ISSUE THREAD

**Issue by FaTony** [mate-desktop/mate-terminal#140]
Here's what output I get:

(mate-terminal:15509): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2202:16: not a number

(mate-terminal:15509): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2202:16: Expected a string.

(mate-terminal:15509): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3157:14: not a number

(mate-terminal:15509): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3157:14: Expected a string.

(mate-terminal:15509): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3658:14: not a number

(mate-terminal:15509): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3658:14: Expected a string.

(mate-terminal:15509): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3959:62: Using one color stop with linear-gradient() is deprecated.

(mate-terminal:15509): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3992:61: Using one color stop with linear-gradient() is deprecated.

(mate-terminal:15509): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4008:61: Using one color stop with linear-gradient() is deprecated.

(mate-terminal:15509): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4024:59: Using one color stop with linear-gradient() is deprecated.

(mate-terminal:15509): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4038:62: Using one color stop with linear-gradient() is deprecated.

(mate-terminal:15509): Gtk-WARNING **: Theme parsing error: mate-applications.css:214:16: not a number

(mate-terminal:15509): Gtk-WARNING **: Theme parsing error: mate-applications.css:214:16: Expected a string.

(mate-terminal:15509): Gtk-WARNING **: TerminalWindow 0x55d1e624c4f0 is drawn without a current allocation. This should not happen.

(mate-terminal:15509): Gtk-WARNING **: GtkBox 0x55d1e6260170 is drawn without a current allocation. This should not happen.

(mate-terminal:15509): Gtk-WARNING **: GtkVScrollbar 0x55d1e6556310 is drawn without a current allocation. This should not happen.

(mate-terminal:15509): Gtk-WARNING **: GtkMenuBar 0x55d1e641c180 is drawn without a current allocation. This should not happen.

(mate-terminal:15509): Gtk-WARNING **: GtkImageMenuItem 0x55d1e64242c0 is drawn without a current allocation. This should not happen.

(mate-terminal:15509): Gtk-WARNING **: GtkAccelLabel 0x55d1e64233c0 is drawn without a current allocation. This should not happen.

(mate-terminal:15509): Gtk-WARNING **: GtkImageMenuItem 0x55d1e6427380 is drawn without a current allocation. This should not happen.

(mate-terminal:15509): Gtk-WARNING **: GtkAccelLabel 0x55d1e6426b90 is drawn without a current allocation. This should not happen.

(mate-terminal:15509): Gtk-WARNING **: GtkImageMenuItem 0x55d1e642b470 is drawn without a current allocation. This should not happen.

(mate-terminal:15509): Gtk-WARNING **: GtkAccelLabel 0x55d1e6429d50 is drawn without a current allocation. This should not happen.

(mate-terminal:15509): Gtk-WARNING **: GtkImageMenuItem 0x55d1e642bbb0 is drawn without a current allocation. This should not happen.

(mate-terminal:15509): Gtk-WARNING **: GtkAccelLabel 0x55d1e642db90 is drawn without a current allocation. This should not happen.

(mate-terminal:15509): Gtk-WARNING **: GtkImageMenuItem 0x55d1e6432470 is drawn without a current allocation. This should not happen.

(mate-terminal:15509): Gtk-WARNING **: GtkAccelLabel 0x55d1e6433590 is drawn without a current allocation. This should not happen.

(mate-terminal:15509): Gtk-WARNING **: GtkImageMenuItem 0x55d1e644e290 is drawn without a current allocation. This should not happen.

(mate-terminal:15509): Gtk-WARNING **: GtkAccelLabel 0x55d1e644aba0 is drawn without a current allocation. This should not happen.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by raveit65** [comment]
It is not allowed to work on reports without infos like distro, mate version and package version.
