### ISSUE TITLE
MATE terminal blank and unusable.

### ISSUE THREAD

**Issue by Michael-AU** [mate-desktop/mate-terminal#141]
On my machine MATE terminal has stopped working, this happened at the same time as the events in this report on caja https://github.com/mate-desktop/caja/issues/639 (I do not know if they are linked but it seems strange that they both happened at the same time. Initially this was on an old install of MATE Stretch, currently a completely new install with new /home so no settings cross over.

All that happens is I open MATE terminal from the menu it starts but is completely blank. as per screenshot.
![mate-terminal](https://cloud.githubusercontent.com/assets/4082295/18611409/61946686-7d7b-11e6-9c28-04992fb528ab.png)
I try to type in and nothing happens. I change themes to see if the font setting is the problem nothing changes. I type and try to highlight the terminal area and nothing shows. I have had to install xterm to get a usable terminal.

If you need more information let me know.
##

**Comment by Michael-AU** [comment]
Just created a new user and terminal is working for new user, is this an intermittent problem?

**Comment by monsta** [comment]
It was probably just another issue of MATE 1.14 not fully compatible with GTK+ 3.21/3.22 in Debian Testing and Unstable. It should be fixed now with 1.16.
