### ISSUE TITLE
I suggest show warning if there is a foreground process, like gtk2 in the past

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/mate-terminal#149]
In the past, with gtk2, when closing root account, we saw this warning:

![gx8uyeg](https://cloud.githubusercontent.com/assets/7734191/19207549/39ef69d8-8cf2-11e6-8a14-5d560858c56c.png)

Now, with gtk3, mate-terminal closes without warning

I suggest maintain this warning, because it prevents closing mate-terminal accidentally when we are doing important things with the root account
##

**Comment by raveit65** [comment]
Indeed the warning is gone.
This is one of the first annoying things which i disabled normal after Installation :)
Btw. you could disable this in the past for the root account with 'sudo dconf-editor' too.
So we have a non working feature (gsettings key) here.

**Comment by sc0w** [comment]
I have the key **/ org / mate / terminal / global / confirm_window_close** set to **true**

I see on **/ src / terminal-window.c**

https://github.com/mate-desktop/mate-terminal/blob/master/src/terminal-window.c#L3455

`do_confirm = g_settings_get_boolean (settings, "confirm-window-close");`

**Comment by sc0w** [comment]
the **gsettings key** is fine

the problem is the function **terminal_screen_has_foreground_process**, always return **FALSE**

used on **terminal-window.c** and declared on **terminal-screen.c**

**Comment by monsta** [comment]
Wait... "root account"?

**Comment by raveit65** [comment]
> Wait... "root account"?

Header is misleading, there is no different for the warning if you use the terminal as root or not.
Only for disable the warning for root you need to run ' su dconf-editor'

**Comment by sc0w** [comment]
well, after run the command **su**

I mean:  if there is a foreground process

**Comment by monsta** [comment]
Thanks, it works fine now.

**Comment by stefanct** [comment]
Just to confirm, does the fix also re-introduce the `confirm-window-close` functionality (which warns similarly to the running process case but for quitting with multiple open tabs)? This is not working either in my 1.12.1 and I fall for this all the time on multi-monitor setups for some reason :)

**Comment by sc0w** [comment]
@stefanct this was fixed in mate-terminal 1.18, if you don't have in your distribution, talk about this to your package maintainer

**Comment by sc0w** [comment]
@stefanct you need https://github.com/mate-desktop/mate-terminal/commit/d4234710b56581f862c9f0286055028237235ea1 and https://github.com/mate-desktop/mate-terminal/commit/5f9f682483363724c08f596902fbf91a49ac1fb1

**Comment by monsta** [comment]
Well, I thought it worked in earlier releases, like 1.12. It accidentally broke when we moved to GTK+3 build in 1.16, and that's what this report is about.

**Comment by monsta** [comment]
@stefanct: do you use Ubuntu MATE 16.04?

**Comment by stefanct** [comment]
@monsta yes, but i can wait for a newer (Ubuntu) release - just wanted to make sure this feature is still supported and not "optimized" away ;) Thanks for all the helpful replies!

**Comment by monsta** [comment]
Ok, I'll check it there, I still have a VM with 16.04 somewhere in the archive...

**Comment by monsta** [comment]
Hmm looks like `confirm-window-close` option has a bit misleading name and description... it actually asks for confirmation only when some process is currently running in some tab. If nothing is running in any tab, it won't ask.

**Comment by stefanct** [comment]
I thought there were two possible warnings previously (but re-reading this thread this may be wrong). One that is triggered while any tab has a running subprocess (which is always on), and another one that is toggleable by `confirm-window-close` that is shown if you try to close a window with multiple terminal tabs open. The description of the latter is pretty definite IMHO "Whether to ask for confirmation when closing a terminal window which has more than one open tab."

**Comment by monsta** [comment]
Yes, that's why I said it's misleading... but I think it always worked this way and still does. I might remember wrong though... did you see a different behavior in 1.8, for example?

**Comment by stefanct** [comment]
Your last post confuses me even more :) What is "this way"?

I have only the one from Ubuntu 16.04 to test at the moment (1.12.1) and I wrote the initial post because I am rather too lazy to build it from git to test ;)

**Comment by stefanct** [comment]
I have now built mate-terminal from latest git master and the confirm-window-close option does not work as it is described. Shall I open a new issue?

**Comment by stefanct** [comment]
And after looking at the source it is clear what you meant. The code that is triggered by the `confirm-window-close` setting, checks all tabs with `terminal_screen_has_foreground_process` contradicting its description. Looking at the referenced patches now... I don't understand yet how we ended up with that.

**Comment by stefanct** [comment]
So I would have guessed we ended up like that because of some changes way back that broke the close on multiple tab behavior and @sc0w's and @monsta's being unaware of the original meaning and description of the gsettings. However, I checked the initial commit and there the basic behavior is the same. So either the multiple-tabs-open warning was broken before the fork, or I imagined its previous existence altogether.

Anyway, the description of `confirm-window-close` is wrong in any case and I want to get the description's behavior aded. So let's suppose I would like to fix this issues and add a warning if multiple tabs are opened (no matter if they have running subprocesses or not).
How about adding a new gsettings for that (which uses the old description) and make that configurable too?
I personally would already be happy with making the running-process warning permanent (non-configurable) and implement the multiple-tabs checks as currently described but I believe there would be some people become unhappy by this. However, I would enable both checks on default/new installs (I don't know how, yet).

What do you think?

**Comment by sc0w** [comment]
@stefanct it works fine here with multiple tabs, with mate-terminal 1.18.1 and the latest git master, all is fine here

the key **/ org / mate / terminal / global / confirm-window-close** set to **true** works

@monsta @raveit65 it works for you?

**Comment by stefanct** [comment]
Could you please define what "works" mean to you because its behavior on my host clearly does not match the description of `confirm-window-close`.

**Comment by raveit65** [comment]
> I am rather too lazy to build it from git to test ;)

If you are to lazy than i am to lazy to test something which isn't my standard config.
I always disable this unneeded confirmation-dialog.

**Comment by stefanct** [comment]
@raveit65 that's the spirit! Thanks for being such a nice community member (and apparently even too lazy to read the post after that and the following half dozen messages by me, exactly explaining what's wrong and offer to fix it).

**Comment by raveit65** [comment]
unsuscribed.....

**Comment by monsta** [comment]
Looked at gnome-terminal's history... so the original option had been added [in 2004](https://git.gnome.org/browse/gnome-terminal/commit/?id=ea005e334491876bddd3df300841da8e5f227701), the behavior had been changed [in 2008](https://git.gnome.org/browse/gnome-terminal/commit/?id=bac3fe8f3105ea353606fd6ea723a735a5eb58a2). They've renamed the option later during [GSettings port](https://git.gnome.org/browse/gnome-terminal/commit/?id=2bff4b63ed3ceef6055e35563e9b0b33ad57349d). It was done after mate-terminal fork.
