### ISSUE TITLE
backport default solarized gnome-terminal color themes

### ISSUE THREAD

**Issue by ghost** [mate-desktop/mate-terminal#151]
please
##

**Comment by egmontkob** [comment]
https://git.gnome.org/browse/gnome-terminal/commit/?id=b4d7416
https://git.gnome.org/browse/gnome-terminal/commit/?id=2763ea6

**Comment by monsta** [comment]
@egmontkob: thanks, I've created https://github.com/mate-desktop/mate-terminal/pull/213 for testing these themes.
