### ISSUE TITLE
Scrollbar and menus are ignoring system lool and feel.

### ISSUE THREAD

**Issue by BenFenner** [mate-desktop/mate-terminal#154]
Environment: Arch Linux (64-bit) with MATE Desktop Environment 1.16.1 using Redmond theme.
MATE Terminal version: 1.16.1

After updating to 1.16.1 I've noticed the terminal scrollbars no longer honor the system look and feel. All windowed applications should honor the system look and feel.

I'm attaching a screenshot of the new behavior, and an example of a program behaving as desired.

MATE Terminal scrollbar behaving badly on my system (the look is wrong, and the up/down arrows are missing):
![misbehaving scrollbar](https://cloud.githubusercontent.com/assets/34834/20068938/971553ee-a4e8-11e6-8d84-e5f10a51112b.png)

Pale Moon scrollbar behaving well on my system (the look is correct, and the up/down arrows are present):
![scrollbar behaving well](https://cloud.githubusercontent.com/assets/34834/20068939/971645a6-a4e8-11e6-9cd4-5cd1516e077e.png)

**Comment by BenFenner** [comment]
Come to think of it, the menus are also now ignoring the system look and feel. See the screenshots above for that as well.

**Comment by raveit65** [comment]
Your fault :)
We switched mate-terminal to gtk3 with 1.16 .
Looks like your theme does not support gtk3, in result adwaita theme is used for gtk3 applications as fallback if a gtk theme don't support gtk3.
I suggest to use a proper theme ;)
