### ISSUE TITLE
add ability to use middle mouse button to close tabs

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/mate-terminal#155]
caja has this improvement with https://github.com/mate-desktop/caja/commit/ed977d25e487400f547997f95802d139e4fce26b and https://github.com/mate-desktop/caja/commit/4c7f59163c415140d76330a1b3c57b1efe35ca14

and pluma with https://github.com/mate-desktop/pluma/commit/9d1bf65037d56ced8c3d4396902e83e286222914

@bl0ckeduser can you help us?

**Comment by bl0ckeduser** [comment]
I can't get the dependencies installed right currently, I think my
distro is too old, although later I might try to boot a newer distro
and use that

Thanks

blockeduser

**Comment by bl0ckeduser** [comment]
I attached a patch that is against version 1.8, you should be able to port it to the master bleeding-edge as-is version too, but I cannot verify that myself because my distro is too old. Anyway let me know if the fix works for you, thanks, blockeduser

**Comment by sc0w** [comment]
It works for me, you can open pull request for the master branch if you like, or I can do it

only left fix the alineations of the lines 2850 2851

thanks
```patch
diff --git a/src/terminal-window.c b/src/terminal-window.c
index d9986c5..44536c5 100644
--- a/src/terminal-window.c
+++ b/src/terminal-window.c
@@ -2847,8 +2847,8 @@ notebook_button_press_cb (GtkWidget *widget,
         tab_clicked = find_tab_num_at_pos (notebook, event->x_root, event->y_root);
         if (tab_clicked >= 0)
         {
-           update_tab_visibility (window, -1);
-	   gtk_notebook_remove_page(notebook, tab_clicked);
+            update_tab_visibility (window, -1);
+            gtk_notebook_remove_page(notebook, tab_clicked);
         }
     }

**Comment by raveit65** [comment]
merged https://github.com/mate-desktop/mate-terminal/commit/4d5943140d423c9148a9f9118ae638fba905bfb8
Thank you

**Comment by monsta** [comment]
Thanks @bl0ckeduser and @sc0w - works fine here. :smile:

**Comment by sc0w** [comment]
@bl0ckeduser thanks a lot :)
