### ISSUE TITLE
 No warning when closing a terminal with a running process 

### ISSUE THREAD

**Issue by elcste** [mate-desktop/mate-terminal#159]
I'm using mate-terminal 1.16.0-1 on Ubuntu MATE 16.10 (default package with all updates applied).

There's no warning when closing a terminal window (or tab) with a running process. For example, run `top` and then try to close the window — it just closes.

I installed and ran `gnome-terminal` and again started `top`. When I try to close the window it opens a dialog warning about killing the process: 

> **Close this terminal?**
> There is still a process running in this terminal. Closing the terminal will kill it.

I made a new user account and tried there to make sure it wasn't a setting I messed up, but it's the same. I [posted to the Ubuntu MATE community](https://ubuntu-mate.community/t/no-warning-when-closing-a-terminal-with-a-running-process-16-10/10571/), where another user confirmed the same issue and said it did not occur for them on 16.04.

**Comment by monsta** [comment]
Reported at https://github.com/mate-desktop/mate-terminal/issues/149 and fixed.

We will release a new 1.16.x version with the fix soon.

**Comment by elcste** [comment]
I guess I didn't look enough through the closed issues. Thanks!

**Comment by tonikasch** [comment]
Sorry for reopening, but I would like to know if it is going to be fixed for 1.16.x soon.

Thanks in advance

**Comment by monsta** [comment]
Ok, 1.16.2 is released with the fix. Sorry about the delay, we found some more issues and had to spend some time on them.
