### ISSUE TITLE
Closing confirmation window is missing

### ISSUE THREAD

**Issue by mykhi** [mate-desktop/mate-terminal#166]
In 1.16.1 the closing confirmation window is missing even though the setting:
org.mate.terminal.global confirm-window-close is ticket to true.

**Comment by monsta** [comment]
Reported at https://github.com/mate-desktop/mate-terminal/issues/149 and fixed, new version will be released soon

**Comment by monsta** [comment]
Version 1.16.2 is released with the fix.
