### ISSUE TITLE
"Set Title..." does not change window/tab title

### ISSUE THREAD

**Issue by honza889** [mate-desktop/mate-terminal#172]
Affected version: **1.16.2**

When I use **Terminal - Set Title** (or leftclick on tab - Set Title), title is saved (when I reopen the same dialog, the title is here), but window/tab title stay unchanged ("Mate Terminal" stay here).

Setting title using `mate-terminal --title="SOME TITLE HERE"` works ok, but also stay unchanged when I try to change it using **Terminal - Set Title**.

**Comment by kscd** [comment]
The bug you mentioned does not appear on my machine. I am using version 1.16.1 on Debian 9.0.

**Comment by gpezza2** [comment]
can confirm this bug on CentOS 7 running mate-terminal 1.16.2

**Comment by honza889** [comment]
I confirm global setting using **Profile Preferences - Initial title** works, but setting for given terminal/tab using *Terminal - Set Title* still does not work.

**Comment by senlog** [comment]
As @honza889 mentioned, I too face the same issue. Set title on a Mate terminal doesn't do anything.
MATE Desktop Environment 1.16.2

**Comment by senlog** [comment]
Never mind, I have found the option to fix this.  Set the following option to make it work.
Edit -> Profile preferences -> Title and command (tab) 
when terminal commands set their own titles: Replace initial title.

**Comment by honza889** [comment]
+1 + I am also not able to reproduce on **Mate terminal 1.18.1** -> closing.

**Comment by Peter-Kuykendall** [comment]
**SOLVED!**

The problem was my .bashrc file, which was installed by default as part of the Mint 19 Mate 64 package.  It forces the window titles to a default value.  Snippet:

```
# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac
```

I just commented out all those lines and now it works properly!

**Comment by HashRocketSyntax** [comment]
`Replace initial` should be the application default.

**Comment by DougDinsdale** [comment]
> **SOLVED!**
> 
> The problem was my .bashrc file, which was installed by default as part of the Mint 19 Mate 64 package. It forces the window titles to a default value. Snippet:
> 
> ```
> # If this is an xterm set the title to user@host:dir
> case "$TERM" in
> xterm*|rxvt*)
>     PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
>     ;;
> *)
>     ;;
> esac
> ```
> 
> I just commented out all those lines and now it works properly!

it does indeed work, thank you for pointing the issue out.

**Comment by ghuser** [comment]
To me what worked was the opposite to what is proposed above: Edit -> Profile preferences -> Title and command (tab)
"when terminal commands set their own titles:" **Append initial title.** (it was `Replace initial title` and would not work)

For some reason what is set with "-t" is considered initial title which then is somehow changed to username@hostname. 
So appending initial title solves the issue (I guess `prepend` and `keep` would work also, but **not Replace initial title**).
