### ISSUE TITLE
Add preferences option to disable "Middle click to close" functionality.

### ISSUE THREAD

**Issue by annunaki2k2** [mate-desktop/mate-terminal#184]
The option was added with bug #155/#156, and I'm sure for many users it's a great new feature. However, for me, as a clumsy laptop touchpad user, it has caused a number of accidental tab closures and ensuing headaches when I'm tab switching and meaning to middle click paste something.

Please can we have an option to disable this somewhere/somehow?

A huge thanks in advance.

**Comment by sc0w** [comment]
@annunaki2k2 if we change the behavior to close the tabs only if the button is released, do you think this issue can be solved?

**Comment by annunaki2k2** [comment]
I'm not sure it would help unfortunately - the problem is that it's often a very quick thing: highlight text in one place, middle click to paste it, and whomp, tab closed. What you're proposing would allow you to stop something that you've realised is about to happen, but when you're using the three finger soft tap to paste on a laptop touchpad, I don't think this behaviour change would particularly help.

**Comment by jhasse** [comment]
What do you think about an in-app-notification like "Tab closed  [Undo]", which would restore the closed tab along with all of its history.
