### ISSUE TITLE
Missing "select all" keyboard shortcut

### ISSUE THREAD

**Issue by yosifkit** [mate-desktop/mate-terminal#191]
#### Expected behaviour
A keyboard shortcut for "select all", like `ctrl+shift+a`.

#### Actual behaviour
No keyboard shortcut for "select all".

#### Steps to reproduce the behaviour
Open edit menu and see no shortcut. Open "Keyboard Shortcuts..." to go assign one. It it not there. It is not even given a accel_path in the code:

https://github.com/mate-desktop/mate-terminal/blob/5c6f10892aed32bf7c450962119f65c470898d6d/src/terminal-accels.c#L49-L74

#### MATE general version
1.18.0 and 1.16.0

#### Package version
1.18.1 and 1.16.3

#### Linux Distribution
Gentoo and Debian Stretch

#### Link to downstream report of your Distribution
No link

**Comment by monsta** [comment]
Ok, this is now implemented by https://github.com/mate-desktop/mate-terminal/pull/198.
