### ISSUE TITLE
Add option to permanently hide menubar like gnome-terminal

### ISSUE THREAD

**Issue by Justinzobel** [mate-desktop/mate-terminal#193]
#### Expected behaviour
Ability to hide menubar by default

#### Actual behaviour
No option

#### Steps to reproduce the behaviour
Hide menubar using View > Show Menubar
Re-open MATE Terminal

#### MATE general version
1.18

#### Package version
1.18.1

#### Linux Distribution
Solus

#### User Notes:
`gsettings set org.gnome.Terminal.Legacy.Settings default-show-menubar false` is the GNOME Terminal option. Or it can be disabled by Edit > Preferences > General > "Show menubar by default in new terminals"
![screenshot from 2017-09-06 15 03 14](https://user-images.githubusercontent.com/1370117/30095914-9505df86-9314-11e7-820c-d1ca4d7cfff2.png)

**Comment by raveit65** [comment]
I agree with adding a setting for this but i do not agree with disable the menu bar by **default**.
....we are MATE not GNOME.

**Comment by Justinzobel** [comment]
Sorry bad wording, add the option to disable it permanently, not by default for all users :)

**Comment by sc0w** [comment]
mate-terminal have that feature, you can hide the menubar by default:

edit -> profile preferences -> general -> show menubar by default in new terminals

**Comment by Justinzobel** [comment]
WTF @sc0w how did I miss that? Thanks!
