### ISSUE TITLE
Terminal closes while editing keyboard shortcuts

### ISSUE THREAD

**Issue by sain2424** [mate-desktop/mate-terminal#197]
#### Steps to reproduce the behaviour
1. Open MATE Terminal: Go > Keyboard Shortcuts
2. Keep editing shortcuts for some time
3. Terminal will close without any notice

Open terminal again and repeat process 1-3 and it keeps closing without any notice.

#### Additional Information
I changed switch to tab 1-9 from Ctrl + number to Alt + number
Now I am trying to change back to Ctrl + number

#### MATE general version
MATE 1.18.0

#### Linux Distribution
Ubuntu MATE Release 17.04 (Zesty Zapus) 64-bit

**Comment by monsta** [comment]
It's caused by a patch for GTK+3 in Ubuntu. Can't be fixed at our level.
See https://bugs.launchpad.net/bugs/1667227 for more info.
