### ISSUE TITLE
Find Next and Find Previous don't work

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/mate-terminal#199]
It doesn't work in mate-terminal 1.18.1, 1.16.3 and 1.14.0 (debian testing/buster)

It works in mate-terminal 1.8.1 (debian jessie VM)

**Comment by monsta** [comment]
I see that - but only in Debian systems for some reason. Menu items for both actions are greyed out, and keybindings don't work. But it doesn't happen in various Ubuntu releases. :confused:

**Comment by sc0w** [comment]
@monsta weird, what mate-terminal ubuntu version works for you?

**Comment by monsta** [comment]
I tried several systems and mate-terminal versions.

Works with:
- git master, Mint 18.2 [based on Ubuntu 16.04]
- 1.18.1, LMDE 2 [based on Debian Jessie]
- 1.18.1, Ubuntu MATE 17.10
- 1.18.0, Ubuntu MATE 17.04
- 1.16.3, Mint 18.1 [based on Ubuntu 16.04]

Doesn't work with:
- git master, Debian Stretch
- git master, Debian Testing
- 1.16.3, Debian Stretch

**Comment by raveit65** [comment]
>  Menu items for both actions are greyed out, and keybindings don't work.

Problem exists in fedora 26 with builds from 1.19.x and 1.18.1.
Problem with vte?
[rave@mother mate-terminal-compile]$ rpm -qa vte291*
vte291-0.48.4-1.fc26.x86_64

**Comment by monsta** [comment]
Not sure - Ubuntu 17.10 also has 0.48.4, and the feature works...

**Comment by raveit65** [comment]
Issue still exists in f25 with m-t-1.18.1 and
[rave@f25 ~]$ rpm -qa vte291
vte291-0.46.3-1.fc25.x86_64

**Comment by raveit65** [comment]
But i know that ubuntu vte291 is patched and use fixes for other issues which aren't in vte291 git, ie.
a working background from gtk theme settings.

**Comment by sc0w** [comment]
with gnome-terminal 3.26.1 it works

**Comment by monsta** [comment]
Need to check when/why the menuitems for these actions can be disabled.

**Comment by monsta** [comment]
Ok, Ubuntu 17.10 indeed has some patch related to regular expressions for VTE 0.48.

Previous Ubuntu versions and Debian Jessie use VTE older than 0.46, so the problem can't appear there.

**Comment by monsta** [comment]
As I found out, in Ubuntu 17.10 #200 has the reverse effect, probably due to their VTE patch. Search shortcuts worked before, now they didn't. I don't know what they did with VTE, and we need the fix for other distros, so it's merged now.

@flexiondotorg FYI
