### ISSUE TITLE
Make Munity theme available out of box for any distribution

### ISSUE THREAD

**Issue by Ygarr** [mate-desktop/mate-terminal#204]
#### Expected behaviour
Getting Unity like appearance and experience

#### Actual behaviour
no unity like look even through mate-tweak and on 1.19 version

#### Steps to reproduce the behaviour
no cases. mate-dock-applet make partially look, but no top-menu applet.

#### MATE general version
1.18 or 1.19

#### Package version
 apt show mate-desktop
Package: mate-desktop
Version: 1.18.0-1
Priority: optional
Section: x11
Maintainer: MATE Packaging Team <pkg-mate-team@lists.alioth.debian.org>
Installed-Size: 100 kB

#### Linux Distribution
mageia, debian, arch, sabayon(gentoo).- seems all them, except originally Ubuntu 17.10.

#### Link to downstream report of your Distribution
moved to: https://github.com/mate-desktop/mate-applets/issues/285

**Comment by raveit65** [comment]
Why should MATE looks in all distros like unity?
If you like to see such a specific theme in other distros than ubunu you have to file out out a report there ask distro maintainer to add the theme.
Filing out a report here is the wrong place because we have no influence about distros.
