### ISSUE TITLE
Add an option to use dark Gtk theme variant

### ISSUE THREAD

**Issue by jhasse** [mate-desktop/mate-terminal#210]
I'm using a light theme for most applications except for my terminal.

Similar to https://falstaff.agner.ch/2014/04/18/enable-dark-theme-in-gnome-terminal-3-12/

**Comment by flexiondotorg** [comment]
Dark variants support is being dropped from GTK so adding this is unnecessary.

**Comment by jhasse** [comment]
> Dark variants support is being dropped from GTK so adding this is unnecessary.

Intersting, do you have a source for that?

**Comment by monsta** [comment]
@flexiondotorg: is it also true for window manager themes? See https://github.com/mate-desktop/marco/issues/105.

**Comment by flexiondotorg** [comment]
I believe so. My understanding is dark variants should be implemented as entirely standalone theme.

**Comment by jhasse** [comment]
I've asked on the Gtk+ IRC and they said that this will still be supported.

If I understand it correctly dark variants should be implemented as a new theme (meaning they need to be selected as a new theme in GNOME Teaks for example), but the dark theme request will still work regardless (see https://git.gnome.org/browse/gtk+/tree/gtk/gtksettings.c#n820).

@flexiondotorg Can you reopen this issue?

**Comment by matthiasclasen** [comment]
If an applictation prefers the dark theme because it needs to show content without distractions (say, a photo viewer), then the gtk-application-prefers-dark-theme setting is still the way to do that. If a user wants to use a dark theme for all applications, then there is now a separate dark theme for them.
