### ISSUE TITLE
Please install .appdata.xml file to correct metainfo location

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/mate-terminal#229]
In Debian, the .appdata.xml (apspstream) file goes into /usr/share/metainfo.

See here for the workaround, I currently have in debian/rules:
https://anonscm.debian.org/cgit/pkg-mate/mate-terminal.git/commit/?id=366b941838ee8dc84dcbf9b064201ef15b3b71a9

**Comment by monsta** [comment]
Fixed in https://github.com/mate-desktop/mate-terminal/commit/000df06686484a2ed78c701088868c864dd0fb45, picked to 1.20 branch in https://github.com/mate-desktop/mate-terminal/commit/82c02f815f3be21fa899d8eb3513ba494f04f489.
