### ISSUE TITLE
mate-terminal can't set transparency on ubuntu 18.04 daily distribution

### ISSUE THREAD

**Issue by liuyi92** [mate-desktop/mate-terminal#235]
#### Expected behaviour
When open mate-terminal and set the background transparency to max, the terminal window should be transparent

#### Actual behaviour
When open mate-terminal and set the background transparency to max, the color of terminal window became black

#### Steps to reproduce the behaviour
1.open mate-terminal on ubuntu 18.04 daily distribution
2.click Edit->Profile Preferences->Background, and choose "Shade transparent background",then click the bar to set value of transparency
#### MATE general version
1.20.0-0ubuntu1

#### Package version
mate-terminal-1.20.0-0ubuntu1

#### Linux Distribution
ubuntu 18.04 daily

**Comment by liuyi92** [comment]
I found in gnome-terminal source code, in terminal-screen.c , a function update_toplevel_transparency() called by update_color_scheme() may be the key.

**Comment by liuyi92** [comment]
liuyi@liuyi-Vostro-3900:~$ gsettings get org.mate.Marco.general compositing-manager
true
Should I change the value of this?

**Comment by liuyi92** [comment]
But I think I am using gnome-shell as the window manager now,not marco ...

**Comment by raveit65** [comment]
> Should I change the value of this?

You can try, but gnome-shell use mutter as WM which has a compositor.
As it is working in MATE session i suggest to use MATE.
And sorry, i don't use gnome-shell, so i am not able to reproduce the issue.

**Comment by liuyi92** [comment]
@raveit65 em...I know that. Thanks any way!

**Comment by liuyi92** [comment]
Referencing to gnome-terminal, I made a patch to resolve this , I think there may be someone else use mate-terminal in other desktop environment just like GNOME3.

**Comment by lukefromdc** [comment]
Both the issue and the fix confirmed as I have gnome-shell installed for "competition comparison" proposes.

**Comment by monsta** [comment]
Same as https://github.com/mate-desktop/mate-terminal/issues/143?

**Comment by raveit65** [comment]
fixed
https://github.com/mate-desktop/mate-terminal/commit/e1b834a2bf684ac4a7d4b33fbf216d65896889c6

**Comment by flexiondotorg** [comment]
And uploaded a patched version to Ubuntu 18.04.

**Comment by MASHtm** [comment]
this patch causes a transparent menu bar on F27 with Adwaita Theme and Compiz. I downloaded and rebuilt the current mate-terminal-1.20.0-1.fc27.x86_64 and commented out the code from this patch and I have back my usual (nontransparent) menu bar.

**Comment by raveit65** [comment]
Only with adwaita theme?
What is the result with BlueMenta (fedora-mate-default)?

**Comment by MASHtm** [comment]
bluementa works. It also works on two other machines were I use adwaita/compiz as well. I've not found the difference in the user-profile yet what causes this on my desktop machine. But rebuilding the RPM without the patch fixed it. I opened a new bug #240 as well.

**Comment by raveit65** [comment]
Maybe a different in compiz-reloaded config?

**Comment by raveit65** [comment]
I will simply revert the culprit commit for fedora builds as a working transparancy background in gnome-shell doesn't have a high priority for me.
I suggest to do the same here.

**Comment by lukefromdc** [comment]
I agree with reverting this, and have also seen a transparent menubar in Adwaita even while running in a MATE session with compiz

**Comment by monsta** [comment]
Ok, let's revert it and then reopen https://github.com/mate-desktop/mate-terminal/issues/143 (as this one seems to be duplicate of it).

**Comment by monsta** [comment]
Ok, the commit is now reverted (https://github.com/mate-desktop/mate-terminal/commit/c4cedf761d77f8586d067a1da34204ecb5810fa7)
