### ISSUE TITLE
Active tabs indistinguishable from inactive

### ISSUE THREAD

**Issue by abourget** [mate-desktop/mate-terminal#238]
I'm on Ubuntu 17.10, with Unity (had issues with Gnome 3).

I remember solving the very low-contrast tabs on Gnome-Terminal, but now I'm back with a verrrry low contrast active tab.. text is the same color on all tabs, and a very thin shadow on the sides of the tab is the only thing to tell them apart.

What do you think could be done to improve that in this situation ?

**Comment by monsta** [comment]
Most probably it's a theme issue. Which one do you use? Try changing GTK+ theme in Appearance Preferences.

**Comment by abourget** [comment]
Yeah it is a theme issue, so I'm wondering which classes or CSS I could apply to change mate-terminal tabs ?

I remember applying CSS to increase contrast in n gnome-terminal.. does mate use gtknotebooks?

**Comment by lukefromdc** [comment]
MATE does use GtkNotebooks, they've been around since GTK2 and thus GNOME 2

**Comment by abourget** [comment]
ok, I'll need to dig in.. and find which file and which .css fixes that in the latest environments (Ubuntu 17.10)..

I'll post it here if I find it.
