### ISSUE TITLE
updating the screen content in inacive (covered by other tabs)  tabs messes up the content.

### ISSUE THREAD

**Issue by hrebicek** [mate-desktop/mate-terminal#24]
I have the impression, while writing to inactive tabs line breaks are inserted according to the current, visible window, having a different zoom factor, making the display messed up.
(The same issue exists in gnome-terminal and still unsolved.)

**Comment by monsta** [comment]
> The same issue exists in gnome-terminal

Then it's a bug in VTE, the terminal widget library used by both terminals.
Does it still happen here or in gnome-terminal?

**Comment by monsta** [comment]
Well, if there won't be any more feedback, we'll consider it has been fixed at some point, so the report could be closed.
