### ISSUE TITLE
transparency patch for #143/#235 causes transparent menu bar on F27/compiz/adwaita

### ISSUE THREAD

**Issue by MASHtm** [mate-desktop/mate-terminal#240]
The commit https://github.com/mate-desktop/mate-terminal/commit/e1b834a2bf684ac4a7d4b33fbf216d65896889c6 causes a transparent menubar on F27 with compiz and adwaita Theme. I downloaded and rebuilt mate-terminal-1.20.0-1.fc27.x86_64 without the patch and the menubar is correctly displayed again.

**Comment by raveit65** [comment]
I can't reproduce it in f28 with mate-terminal-1.20.0-1
![m-t-compiz-adwaita](https://user-images.githubusercontent.com/961604/39247840-c2bf1050-489a-11e8-9c11-9bf2f6f31a40.png)

**Comment by raveit65** [comment]
Same with f27
![m-t-compiz-adwaita-f27](https://user-images.githubusercontent.com/961604/39249609-4ebd7f84-489f-11e8-913f-d26c02cb6742.png)

Do i miss something?

**Comment by MASHtm** [comment]
I tried some other Control-Themes as well now on the affected machine:
Good: BlackMATE, BlueMenta, Blue-Submarine, GreenLaguna, GreenSubmarine, Menta
Transparent: Adwaita-(Black), Clearlooks, ClearlooksClassic, ContrastHighInverse, Crux, Glider, Glossy, Highcontrast,  Industrial, Mist, Simple

**Comment by raveit65** [comment]
As fedora Mate maintainer my focus is how mate-terminal works in mate-session, but without reproducing it i won't revert the commit in fedora.
And it works for you in 2 boxes.
Well, my f28 screenshot was with nvidia Gt1030 and nvidia-driver from rpmfusion.
f27 screnshot was in qemu-kvm VM and virtio graphic driver.

**Comment by raveit65** [comment]
see adjustments for terminal in BlueMenta theme
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlueMenta/gtk-3.0/mate-applications.css#L878
You can try to add something like this to ~/.config/gtk-3.0/gtk.css
Those file override every theme in user session.

**Comment by MASHtm** [comment]
It's a more basic element from gtk-widgets.css which fixes the issue. If I add
```
/* Default color scheme */
@define-color theme_bg_color #d4d4d4;

/* this controls the general appearance of the menubar */
menubar,
.menubar {
    background-image: linear-gradient(to bottom,
                                      @theme_bg_color,
                                      shade (@theme_bg_color, 0.96));
    border-width: 0;
    -GtkWidget-window-dragging: true;
        text-shadow: none;
}
```
to ~/.config/gtk-3.0/gtk.css menu looks as expected.

**Comment by lukefromdc** [comment]
I've got a similar issue with the selected tab if two or more tabs are open in and only in my UbuntuStudio_Legacy theme. BlackMATE, which shares a fair amount of code with it is OK. Looks like this introduced a need to adjust themes for the terminal

**Comment by raveit65** [comment]
> Transparent: Adwaita-(Black), Clearlooks, ClearlooksClassic, ContrastHighInverse, Crux, Glider, Glossy, Highcontrast, Industrial, Mist, Simple

The gtk2 themes from this list we can ignore as they use the gtk+-3 part from Adwaita as fallback.
But we have no control to fix current gtk+ themes like Adwaita or ContrastHigh themes.
So if it is confirmed that this commit for for gnome session breaks MATE session we should revert it or improve the commit.
But in my test it was all fine with using Adwaita theme in several fedora installations.
Also the reporter says that it happens only on one box, and in 2 others it is fine.

**Comment by lukefromdc** [comment]
We could load a css file at startup to put the theme background color on the menubar and the tabs (which can also get turned transparent by this) as a fallback. Same as 
https://github.com/mate-desktop/mate-panel/commit/45b25410cddde852554b3153e81ad59a5e6722ad
or with the lighter/faster gresource to load it
https://github.com/mate-desktop/mate-panel/commit/217044626cf1aef24ff3090d8d8ce4f380f48658
in mate-panel

**Comment by raveit65** [comment]
Sure, we can work with a css and add a band-aid there.
But is it not better to find out the course of the issue first?
And i am not able to reproduce your theme issue.
![terminal-ubuntu-legacy](https://user-images.githubusercontent.com/961604/39394591-0f1184fc-4ad4-11e8-8a7e-d7a4c0bc5b87.jpg)
Do i miss something?

**Comment by parejkoj** [comment]
I just upgraded from Ubuntu 16.04 to 18.04, and I'm also getting the transparent menu bar when the terminal is focused. What information can I provide to help debug this?

**Comment by lukefromdc** [comment]
We are going to have to fix this by loading a css file it turns out, as now we've got a transparent menubar in Adwaita and Adwaita-Dark when and only when the terminal window is focussed

**Comment by raveit65** [comment]
I will simply revert the culprit commit for fedora builds as a working transparancy background in gnome-shell doesn't have a high priority for me.
I suggest to do the same here.

**Comment by raveit65** [comment]
@MASHtm 
f27 is updated https://bodhi.fedoraproject.org/updates/FEDORA-2018-f35d8a7369

**Comment by LeDechaine** [comment]
Just updated my debian testing and I have the same issue. Affects most of the themes.

Thanks for everything, by the way. Nothing's better than the MATE Desktop Environment. :)

**Comment by raveit65** [comment]
Again, should i revert the culprit commit in our repos too?
@sc0w @monsta @flexiondotorg @lukefromdc

**Comment by lukefromdc** [comment]
I agree with reverting it, it causes too many problems

**Comment by monsta** [comment]
I agreed to revert it in comments at https://github.com/mate-desktop/mate-terminal/issues/235.

**Comment by monsta** [comment]
The revert will probably work for everyone, but just in case, I made it a PR: https://github.com/mate-desktop/mate-terminal/pull/245

**Comment by guy-rouillier** [comment]
I run Ubuntu 18.04 Mate, and just encountered this issue tonight (June 27 2018)after applying some updates.  Mate terminal version 1.20.0.  I'm using Marco with Compton GPU compositor, and the menu bar background is black, which makes the menu unreadable.  If I switch to Marco Adaptive, the menu bar becomes transparent and readable.  Marco no compositor, menu bar is black and unreadable.   With Compiz, the menu bar is transparent when selected, and the title bar color when unselected.  Marco with Compton GPU is the best looking, so I'd prefer to stick with that.

I fired up gnome-terminal, and it is fine with all compositors, but the menubar has a solid car (off-white) and is not transparent.  I guess I'll stick with that until this problem with mate-terminal is fixed.

**Comment by raveit65** [comment]
You better post this to ubuntu bugreport system and ask maintainer to add the fix to ubuntu.
We can't fix that.

**Comment by monsta** [comment]
That's because mate-terminal in 18.04 has the patch from https://github.com/mate-desktop/mate-terminal/commit/e1b834a2bf684ac4a7d4b33fbf216d65896889c6. I've already asked @flexiondotorg to revert the patch.

**Comment by lukefromdc** [comment]
Again, I second backporting this to all affected branches. This is a bugfix and people need it now, not when 3.22 comes out

**Comment by lukefromdc** [comment]
I just looked at the branches, and that (now reverted) patch is not in our repo for 1.20, so nothing to backport on this end. It only ever was applied to git master which became 1.21.0 after it was reverted. Thus, Ubuntu needs to drop their local patch, this is not under our control

**Comment by guy-rouillier** [comment]
Thanks monsta for following through.  So I'm concluding I do not need to post to Ubuntu bug reporting.

**Comment by guy-rouillier** [comment]
Ugh, just upgraded to 18.10 Ubuntu Mate, and this issue is still present.  Ok, this bugs me enough to pursue it.  Where should I go, Ubuntu bug reporting?  Thanks.  Here's a screenshot:

![image](https://user-images.githubusercontent.com/3578941/47406617-41a69c80-d725-11e8-93ed-7aebd085beb6.png)
