### ISSUE TITLE
Hitting arrow keys adds characters in vi editor

### ISSUE THREAD

**Issue by rcaridade145** [mate-desktop/mate-terminal#251]
#### Linux Distribution
Ubuntu 18.04
 
https://askubuntu.com/questions/353911/hitting-arrow-keys-adds-characters-in-vi-editor

Not sure if this belongs, or directly to Ubuntu here but this happened to me on mate-terminal when i was trying to commit some files to git, ended up using nano.

Already installed console-data, but the issue continues. Is this a distribution problem or can it be a issue with vte?

**Comment by lukefromdc** [comment]
This is definately not in mate-terminal, which is basically a wrapper around VTE and provides the menubar, the window, etc. It may be a bug in VI itself (don't know as I use Nano as my terminal text editor) or maybe in VTE?

**Comment by rcaridade145** [comment]
As it is not on mate-terminal i'm going to close it.
