### ISSUE TITLE
Custom command checkbox

### ISSUE THREAD

**Issue by kyrios123** [mate-desktop/mate-terminal#277]
#### Expected behaviour
Have the possibility to check the box "Custom command" in the Profile preference

#### Actual behaviour
Checkbox is missing ([screenshot](https://i.imgur.com/OrMFYAx.png))

#### Steps to reproduce the behaviour
Build mate 1.22.0 from source (In the previous versions I didn't notice this issue)

#### MATE general version
1.22.0

#### Package version
1.22.0

#### Linux Distribution
Solus

#### Link to downstream report of your Distribution
https://dev.getsol.us/D5664

**Comment by raveit65** [comment]
This is removed. See https://github.com/mate-desktop/mate-terminal/pull/227 for detailed references.
In short, `utmp` support is removed from `vte` itself, so this doesn't work any more.

**Comment by raveit65** [comment]
But i can add a custom command with 1.22 in fedora.
![Bildschirmfoto zu 2019-03-10 14-01-38](https://user-images.githubusercontent.com/961604/54085301-212a5800-433d-11e9-87b2-703988576519.png)
You need to add a check a line above.

**Comment by kyrios123** [comment]
Thanks for the explanation @raveit65 
As you said with the above checkbox it works fine.
