### ISSUE TITLE
Add a dark mode like the one in gnome-terminal

### ISSUE THREAD

**Issue by Jacalz** [mate-desktop/mate-terminal#284]
#### Expected behaviour
A dark mode should be available and it should, just like gnome-terminal, make the terminal background very dark but not fully black. This makes it so people with light themes can have a readable terminal when having the option to use theme colours set.

#### Actual behaviour
No dark theme and thus have to fiddle around with a colour wheel.

#### Steps to reproduce the behaviour
1. Open a new terminal
2. Go to the colors tab

#### MATE general version
1.20.1

#### Package version
mate-terminal, version: 1.22.1, release: 11

#### Linux Distribution
Solus

#### Link to downstream report of your Distribution
Well, it's not an issue with Solus in any way from what I can see...

**Comment by raveit65** [comment]
> A dark mode should be available and it should,

Why ?

>  just like gnome-terminal, make the terminal background very dark but not fully black.

Why?

**Comment by Jacalz** [comment]
To answer you first question: 
A user might want to use a light theme (with use theme colors enabled in mate-terminal), but as most people, use a dark background to the terminal. Instead of them having to fiddle around with background colours, it is easier to have the possibility to choose a theme variant like in Gnome terminal. Same can be done if user has a dark theme he can safely and easily use a light theme. In this way the user can have a sane and safe way to switch.

To answer your second question:
A fully dark background doesn't look good from a user interface perspective and might give a bit too much contrast. How often do you see websites with a pure black background?

**Comment by mixmastamyk** [comment]
There is a dark theme, or scheme as the dialog calls it.  It is called "Gray on black."  

Perhaps it is too black but very close to what most folks want.  Not too much contrast due to the gray text.  I personally take "the edge off" the background by setting it to 90% opacity on the background tab.

Perhaps there is room for a "Gray on charcoal" with a background of #222 or something.

**Comment by lukefromdc** [comment]
I use green text on a black background (emulating an early green phosphor CRT) for terminals, GNOME offers a terminal theme very close to what I use as  "green on black" no doubt the same idea. Some early monchrome CRT's used a green phosphor and some yellow, I think it was intended to be easier on the eyes than white.

**Comment by mixmastamyk** [comment]
Cool.  IIRC, Amber Monochrome was known as the "ergonomic choice" back in the day, best for late-night coding sessions.  I think it is the same concept as using redshift/f.lux is today, regarding reducing blue light exposure at night.

**Comment by phu9Suop** [comment]
Hi
I use vi in color mode and need the same appearance both in console and mate-terminal.
vi colored shows like attached. Yellow on white barely visible
![Bildschirmfoto zu 2021-02-04 15-47-59](https://user-images.githubusercontent.com/37701817/106909746-e08e1180-6700-11eb-97af-6359e139fd72.png)
vi colored marked shows like attached and is better visible yellow on black
![Bildschirmfoto zu 2021-02-04 15-55-59](https://user-images.githubusercontent.com/37701817/106910449-85105380-6701-11eb-98ff-2015849951e3.png)
I would appreciate a total black mode for the mate-terminal , independent from the desktop setting

**Comment by lukefromdc** [comment]
Mate-terminal supports setting custom terminal themes "profiles." Go to edit->profiles and check "edit" you then get a screen with 6 available tabs. Select "color" and be sure to uncheck "use colors from system theme" then select the desired foreground and background colors

**Comment by Jacalz** [comment]
I am no longer interested in this change as I am no longer using mate terminal. Going to close this.
