### ISSUE TITLE
Always show tabs

### ISSUE THREAD

**Issue by kogaba** [mate-desktop/mate-terminal#286]
#### Expected behaviour
Tabbar visible with only one tab.

#### Actual behaviour
Tabbar isn't visible with only one tab

#### Steps to reproduce the behaviour
Start the terminal

#### MATE general version
I don't know

#### Package version
1.20.2

#### Linux Distribution
Ubuntu 19.04

#### Link to downstream report of your Distribution
I don't know

**Comment by raveit65** [comment]
wtf! template ignored.
Which forced me to ignore your report.

**Comment by kogaba** [comment]
Dear @raveit65, 
Could you please explain me this reply?
I really don't know what do you mean.
Thank you!

**Comment by kogaba** [comment]
I see I didn't used the post template!
I am a noob sorry. :/
I didn't get that and wasn't sure how to post a feature req.
