### ISSUE TITLE
Not providing timestamps with window manager events

### ISSUE THREAD

**Issue by JimmyAx** [mate-desktop/mate-terminal#29]
The MATE terminal will sometimes(or always?) not provide the correct timestamp with a window event to the window manager.Wwhen window is maximized the following is printed to ~/.xsession-errors:

>Fönsterhanterarvarning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x40008ee (jimmy@debi)
>Fönsterhanterarvarning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.

Fönsterhanterarvarning = Window manager warning

Additionally the following will get written to the file when closing a MATE terminal window:

>Fönsterhanterarvarning: Receiving a NET_CLOSE_WINDOW message for 0x400137c (jimmy@debi) without a timestamp!  This means some buggy (outdated) application is on the loose!
>Fönsterhanterarvarning: Tried to ping a window with CurrentTime! Not allowed.

I'm using mate-netbook at the same time with the only changed setting being that it should undecorate maximized windows (org.mate.maximus -> undecorate)

**Comment by monsta** [comment]
I use terminal every day and I've never encountered this in 1.8 or 1.10. Looks like it can be closed now.
