### ISSUE TITLE
Unable to scroll tabs by mouse wheel in Profile Preferences of MATE Terminal

### ISSUE THREAD

**Issue by N0rbert** [mate-desktop/mate-terminal#297]
#### Expected behaviour
In previous MATE 1.12.1 version (as it was in Ubuntu 16.04 LTS) user was able to scroll tabs of Profile Preferences with mouse wheel.

#### Actual behaviour
In modern MATE versions as in Ubuntu 19.10 (development version) user is unable to scroll tabs of Profile Preferences with mouse wheel.

#### Steps to reproduce the behaviour
1. Open MATE Terminal
2. Go to Edit → Profile Preferences
3. Try to scroll shown tabs with mouse wheel

#### MATE general version
1.22.1

#### Package version
1.22.1-0ubuntu1

#### Linux Distribution
Ubuntu 19.10 (development version)

#### Link to downstream report of your Distribution
https://bugs.launchpad.net/ubuntu/+source/mate-terminal/+bug/1838812

Note: this is usability issue, mate-control-center applets was affected too and bugs were fixed.

**Comment by tamplan** [comment]
Fixed by https://github.com/mate-desktop/mate-terminal/pull/358, can be close.
