### ISSUE TITLE
Argument --name does not work

### ISSUE THREAD

**Issue by thexavier666** [mate-desktop/mate-terminal#298]
#### Expected behaviour
By using `mate-terminal --name=win1`, should create a new terminal and set the variable  `WM_NAME(STRING)=win1`. That is, it should create a terminal with the name as `win1`
 
#### Actual behaviour
Even after using the command, the value is null. It's an unnamed terminal.

#### Steps to reproduce the behaviour
1. Run command `mate-terminal --name=win1` and create a new terminal window (say `ter1`)
2. Run command `xprop` on another terminal
3. Click on `ter1` using mouse and see the value of variable `WM_NAME(STRING)`

#### MATE general version
Mate Desktop Environment 1.20.1 

#### Package version
Mate Terminal 1.20.0

#### Linux Distribution
Ubuntu 18.04, running i3wm

**Comment by rr-** [comment]
`--class` does not work either.

**Comment by thexavier666** [comment]
I temporarily solved my requirement by installing a light terminal called [sakura](https://launchpad.net/sakura)

**Comment by sorsarre** [comment]
Would ```--role``` work?

**Comment by rbuj** [comment]
You can use `-t, --title=TITLE` for setting the window title for a new terminal. You can consult this and other options in the built-in help. Type `mate-terminal --help` or
```
$ mate-terminal --help-terminal-options
Usage:
  mate-terminal [OPTION?]

Terminal options; if used before the first --window or --tab argument, sets the default for all terminals:
  -e, --command                   Execute the argument to this option inside the terminal
  --profile=PROFILE-NAME          Use the given profile instead of the default profile
  -t, --title=TITLE               Set the terminal title
  --working-directory=DIRNAME     Set the working directory
  --zoom=ZOOM                     Set the terminal's zoom factor (1.0 = normal size)

MATE Terminal Emulator
```

**Comment by rr-** [comment]
This is not about titles at all, this is about x11 window properties to make it possible to search for the specific terminal window. --title is useless when your shell (or terminal multiplexer) outputs escape sequences that change it anyway.

I don't understand how a bug report about a clearly broken mechanism can be nonchalantly closed like this.

**Comment by thexavier666** [comment]
I'm not using Gnome any more but the installed version in my PC is `GNOME Terminal 3.28.2 using VTE 0.52.2 +GNUTLS -PCRE2`
`--class` is working
`--name` is still not working

These are specially useful when using tiling window managers. I don't think this issue should be closed.
