### ISSUE TITLE
mate-terminal crashed when I change the profile

### ISSUE THREAD

**Issue by tazou** [mate-desktop/mate-terminal#304]
Hello,
My mate-terminal has crashed when I changed the profile.
I clicked on the menu "Terminal", then "Change profile", then "Default".

#### Expected behaviour
No crash

#### Actual behaviour
The mate-terminal segfault

#### Steps to reproduce the behaviour
I can't reproduce, appears just one time.

#### MATE general version
MATE v1.16.2

#### Package version
mate-terminal v1.16.3-1

#### Linux Distribution
Debian 9.11

#### Informations
I can see it in my "dmesg" after the crash : 
[766344.382766] mate-terminal[16631]: segfault at 1 ip 00007f2b95b26966 sp 00007ffc9cdd29a0 error 4 in libgobject-2.0.so.0.5000.3[7f2b95af2000+52000]

Thank you!
Regards.

**Comment by vkareh** [comment]
Can you reproduce this at all on MATE v1.22? MATE v1.16 is no longer 
supported.

**Comment by tazou** [comment]
I have not MATE v1.22 yet.
If I have one day and the bug appears again, I'll open a new issue.
Thank you,
Regards.
