### ISSUE TITLE
Konsole "Save Output" hangs in MATE Terminal

### ISSUE THREAD

**Issue by SangeethaBusangari** [mate-desktop/mate-terminal#315]
#### Expected behaviour
It should save.

#### Actual behaviour
Hanging

#### Steps to reproduce the behaviour
- selected "Save Output As" on one instance of Konsole
- Got a spinning icon and nothing happened for a long time
- All the other Konsole instances also stopped working and became blank

#### MATE general version
1.16.3

#### Package version
Konsole version: 2.10.5

KDE Version: 4.14.8

**Comment by lukefromdc** [comment]
Konsole is a KDE package and not part of mate-terminal at all.

**Comment by SangeethaBusangari** [comment]
Thank you,
