### ISSUE TITLE
URL highlighting broken since vte 0.60

### ISSUE THREAD

**Issue by cosarara** [mate-desktop/mate-terminal#329]
#### Expected behaviour
URLs should be highlighted in the text when the mouse is over them.

#### Actual behaviour
They aren't.

#### Steps to reproduce the behaviour

* Run mate-terminal
* Go to Edit -> Profile Preferences and ensure the option "Highlight URLs under mouse pointer" is enabled
* type https://mate-desktop.org/ and see that it is not highlighted when hovered with the mouse pointer

#### MATE general version
1.24

#### Package version
mate-terminal 1.24.0-1
vte3 0.60.0-1

#### Linux Distribution
Arch Linux

#### Link to downstream report of your Distribution
https://bugs.archlinux.org/task/65782

See also https://sourceforge.net/p/lxde/bugs/932/attachment/0001-Don-t-use-deprecated-vte_terminal_match_add_gregex.patch for the equivalent patch in lxterminal.

**Comment by alejandro-perez** [comment]
Searching the terminal (menu Search -> Find... / Shift+Ctrl+F) is affected as well.

**Comment by norbusan** [comment]
PR https://github.com/mate-desktop/mate-terminal/pull/330

**Comment by alejandro-perez** [comment]
Thanks! 
Please, if possible, tag it as important and release a mate-terminal 1.24.1 as soon as possible, as for many of us (I'm sure I'm not alone here), searching on the terminal is a key feature for our day to day basis. At the moment I've had to downgrade vte

**Comment by rubyFeedback** [comment]
That would be quite convenient; I personally also follow mostly just the stable branch, since I have had too many problems with gtk/glib-related programs in the past (I compile gtk+glib from source).

**Comment by sc0w** [comment]
It was fixed with https://github.com/mate-desktop/mate-terminal/commit/c21a7b374f420b224c24307325061b3bb55aa3bf in https://github.com/mate-desktop/mate-terminal/pull/330

**Comment by cosarara** [comment]
Would it be possible to make a point release with this so that the patch can get to distros?

**Comment by raveit65** [comment]
Is it possible to use it as patch to get into distros.
Why always a new release for one commit?

**Comment by cosarara** [comment]
Upstream points fingers at the distros, and the distros point fingers at upstream. I don't care who fixes it, I maintain neither, but I know I've been experiencing this bug for almost 3 months now. I think it's a bit weird that the latest stable release can't be used as-is and instead needs a patch on top. I don't know how much effort it is to make a point release, but I hope it isn't too bad.

**Comment by raveit65** [comment]
Well, making new point releases for all repos is on my list, but my list is very very long :)
Sorry, i can't give you a fix date when it will happen.
And i do that all in my spare time.......

If you want it fast ask your distro maintainer to add it as  a patch.
Did you file out a report for it to contact him/her?
Fedora maintainer did it already one month ago https://src.fedoraproject.org/rpms/mate-terminal/c/72f9af5f47804a01a662a03704de76565befff87?branch=master

**Comment by raveit65** [comment]
> .......and the distros point fingers at upstream

Really?
Can you please show me the archlinux bugreport where downstream maintainer pointed with his finger to upstream?
....i can't believe that.

**Comment by sc0w** [comment]
in debian it was fixed with https://salsa.debian.org/debian-mate-team/mate-terminal/-/commit/4ee0a2f988978796de6926cdfe58eb108afe7d2e

**Comment by chrislea** [comment]
I've submitted a `PKGBUILD` to the Arch Issue [here](https://bugs.archlinux.org/task/65782) that applies the patch. I'm pretty new to Arch, so I'm not sure what else I might need to do in order to get somebody to build a patched version and get it into the repos.
