### ISSUE TITLE
mate-terminal doesn't parse long urls properly in terminal irc clients

### ISSUE THREAD

**Issue by dmashal** [mate-desktop/mate-terminal#33]
i.e.

https://plus.google.com/photos/100625103039786059941/albums/5903718657061196401/5903718658962516146?sqi=103904770310171205536&sqsi=b2110420-5a52-406c-ac79-9472b86c4bfe&pid=5903718658962516146&oid=100625103039786059941

terminal must either be resized or copy and pasted

**Comment by Tele42** [comment]
I think I'm seeing this. I use irssi in mate-terminal, freshly recieved line-wrapped urls are detected fine, but when I use page up / page down to move through backscroll, line-wrapped urls are terminated at the end of the first line of the url, until the window is resized, then it returns to the correct behavior.

**Comment by ailin-nemui** [comment]
this could be an issue since the lines are drawn in two parts, in which case the terminal cannot be expected to pick it up as one connected line
