### ISSUE TITLE
Feature request: Give people the freedom to customize the mate-terminal menus again.

### ISSUE THREAD

**Issue by gtnuux** [mate-desktop/mate-terminal#335]
As long as I was looking at the source code again, I decided to to something that I'd been thinking about for a while.  Once upon a time, I could edit the file /usr/share/mate-terminal/terminal.xml to adjust, for example, the configuration of the right-click menu.  Then gresource happened, and this simple option disappeared.

The attached small patch makes it possible again.  If the file $Home/.config/mate/mate-terminal.xml exists, then it is used instead of the embedded resource copy.  The patch could have been even smaller, but I decided to add an error message if mate-terminal.xml has bad syntax.

To use this feature, a person would need to retrieve the terminal.xml file from the source code.  It might be nice to also install a copy, re-named as mate-terminal.xml, in perhaps /usr/share/doc/mate-terminal/  That way it would be included in the binary packages.
Thanks!
-Jeff

 [terminal-window.c.diff.txt](https://github.com/mate-desktop/mate-terminal/files/4400716/terminal-window.c.diff.txt)

**Comment by gtnuux** [comment]
Any chance this might be included in 1.25.0?  I'll be happy to create a pull-request if that would help.
Thanks,
-Jeff

**Comment by rbuj** [comment]
The UI manager is obsolete now and it must be ported to gtkbuilder. In addition, the xml file binds names with actions, which are defined in other files. A regular user should not be able to modify this. In case it needs to be modified, it should be done at the distribution level. IMHO.

**Comment by lukefromdc** [comment]
Closing as this sounds like it would have a lot of practical problems
