### ISSUE TITLE
MATE Terminal 1.24.0 on Manjaro: No more clickable hyperlinks

### ISSUE THREAD

**Issue by EasyReader2** [mate-desktop/mate-terminal#339]
#### Expected behaviour
echo https://www.google.ch
-> clickable hyperlink should appear

#### Actual behaviour
echo https://www.google.ch
-> NO clickable hyperlink appears

#### Steps to reproduce the behaviour
bash
mate-terminal
echo https://www.google.ch

However, clickable hyperlinks appear on xfce4-terminal (Manjaro), having the same vte3 as dependency.

Version:
vte3 0.60.1-1

I also get this error:
bash
mate-terminal
Error:
mate-terminal:26145): VTE-CRITICAL **: 17:06:06.236: void vte_terminal_match_set_cursor_type(VteTerminal*, int, GdkCursorType): assertion 'tag >= 0' failed

#### MATE general version
MATE 1.24.0

#### Package version
mate-terminal 1.24.0-1

#### Linux Distribution
Manjaro
Kernel Linux 5.4.28-1-MANJARO x86_64

**Comment by gtnuux** [comment]
This has been fixed, but isn't yet in the released version.  See, eg.
  https://github.com/mate-desktop/mate-terminal/issues/333
For now, it's not too hard to download the git source (click the "clone or download" button) and build a copy with working clickable links.
Hope this helps,
-Jeff

**Comment by EasyReader2** [comment]
HI Jeff,
Many thanks for your kind reply. That helps. I'm using xfce4-terminal in the meantime. With a symbolic link in ~/.local/bin named 'mate-terminal' the rest of my workflow stays the same. I'm looking forward to the new version through the regular packages
