### ISSUE TITLE
Shift+Ctrl+C / Shift+Ctrl+V don't work - Corresponding menu items are grayed out.

### ISSUE THREAD

**Issue by j3pic** [mate-desktop/mate-terminal#364]
#### Expected behaviour

It should be possible to copy and paste with Shift+Ctrl+C and Shift-Ctrl+V. If there is a configuration item that turns these off, it should be exposed in the Profile Preferences dialog so I can control it.

#### Actual behaviour

Observe that the Copy and Paste menu items are grayed out:
![image](https://user-images.githubusercontent.com/26551894/91609470-7dc06f00-e945-11ea-8f0d-bc23c530b7e7.png)

Therefore, the corresponding keyboard shortcuts don't work. It doesn't matter what key you bind to the function.

Copy is intermittently unavailable, but Paste is never available.

However, the Copy and Paste options in the right-click menu are available when there is a selection or data on
the clipboard, respectively.

![image](https://user-images.githubusercontent.com/26551894/91609833-2078ed80-e946-11ea-8078-3f6d64b65b76.png)

#### Steps to reproduce the behaviour

1. Start up MATE
2. Try to use the Copy and Paste feature.

#### MATE general version

1.20.4, as distributed by Debian.

#### Package version

    # mate-terminal --version
    MATE Terminal 1.20.2

#### Linux Distribution

Debian Buster

#### Link to downstream report of your Distribution

No downstream report made.

**Comment by rbuj** [comment]
Using Shift+Ctrl+C shortcut for copying the selected text on terminal works fine.
