### ISSUE TITLE
MATE Terminal 1.2.1 : tab autocomplete not working when modifying command

### ISSUE THREAD

**Issue by acrobat1** [mate-desktop/mate-terminal#37]
In MATE Terminal 1.2.1 (Linux mint13maya Mate edition) tab autocomplete will not work when trying to modify a previously issued command:it will only work when typing the command for the first time,it won't work when recalling that command from bash history or when  pasting  a command into the shell.

**Comment by acrobat1** [comment]
This is still happening (as far as I can see) all the way up to Mate 1.10 : should I open a new issue ?

**Comment by NiceandGently** [comment]
which distro?

**Comment by infirit** [comment]
Tab completion is not a feature of the terminal emulator like mate-terminal but of the shell.

**Comment by NiceandGently** [comment]
btw. is bash-completion installed, if you use bash as shell?

**Comment by acrobat1** [comment]
I' ll look more in detail and report later on, for now all I can is that I've been seeing such behavior in Mint from a long time now.
BTW, isn't the shell underlying both gnome-terminal and mate-terminal usually always the bash?

**Comment by acrobat1** [comment]
I' ll look more in detail and report later on, for now all I can say  is that I've been seeing such behavior in Mint from a long time now.
BTW, isn't the shell underlying both gnome-terminal and mate-terminal usually always the bash?
