### ISSUE TITLE
Video Streaming(Youtube) via FireFox locks up and freezes entire machine. Hard Reset.

### ISSUE THREAD

**Issue by Kyanite393** [mate-desktop/mate-terminal#377]
I searched open issues for youtube, streaming freeze, as well as libgtk-3.so.0, libglib-2.0.so.0

Found nothing that seemed related sorry if there is already something related...  I could not locate it.

I run OS via External SSD an ADATA 2TB, boots fine. My MoBo's NVMe port does not recognize the drive though pcpartpicker lists it as compatible. Tried pre-formatting and post-formatting on board port will not see... it sure does heat it up though...? So it's in an SSK SSD enclosure connected USB Type C port.

Also have a windows install on a secondary internal HDD that does not boot any longer, get GRUB Repair when attempting to boot the Windows drive.

System Info:
Intel® Core™ i7-6700K CPU @ 4.00GHz × 8 
16gb Ram ADATA
Radeon RX 5500 XT (NAVI14, DRM 3.35.0, 5.4.0-65-generic, LLVM 11.0.0)
Two add'l external HDD non SSD 1TB & 6TB
Three internal 2 TB HDD
Gigabyte Z170MX-Gaming 5 MOBO

#### Expected behaviour
Play video without freezing and making my mouse pointer disappear and keyboard non-responsive

#### Actual behaviour
Video plays for a short while then video freezes, but sound continues to play for a short while, then I am forced to do a hard reset.
This has happened like 5-7 times today. 

Also occassionally get a black screen freeze after computer goes to screensaver then lockscreen happened twice today as well.

#### Steps to reproduce the behaviour
Opening Firefox and playing YouTube vidoes with 4 or more tabs open...

#### MATE general version
MATE 1.24.0

#### Package version
Kernel 5.4.0-65-generic x86_64

#### Linux Distribution
Linux Mint 20.1 Ulyssa 64-bit
Kernel 5.4.0-65-generic x86_64

#### Link to bugreport of your Distribution (requirement)
Here's a few from just today... I have 4 more crash reports if anyone wants to see them let me know I'll pastebin them as well.
https://termbin.com/rhn5
https://termbin.com/f1qn
https://termbin.com/klul

**Comment by lukefromdc** [comment]
That sort of thing sounds like a video driver bug or a Firefox bug, and has nothing to so with the desktop environment. Also, Firefox has nothing to do with mate-terminal other than of course you can run it from mate-terminal. We don't maintain Firefox or video drivers (they are in the kernel) so nothing we can do about it with any of our packages.

**Comment by Kyanite393** [comment]
Never happened to me on any other Distro or Browser... So not sure how Firefox all of a sudden no longer works? Wrote that off quick... Did you even look at the pastebins?

How's freezing after lockscreen Firefox's or my Video Drivers fault?

**Comment by Kyanite393** [comment]
I won't waste my time attempting to make ya'll aware of any issues. Probably go back to a distro that can stream video and wake from sleep.

**Comment by lukefromdc** [comment]
Again: MATE is not a distro, it is a desktop environment. A LOCKSCREEN issue could be the locker, but no package in MATE has anything to do with browsers, videos (youtube included) or video drivers. Same freeze under two or more conditions (one from the locker, one from Firefox) sounds like a GPU lockup, which is a video driver issue.

No I did NOT look at the pastebins as none of this is MATE's fault and I really don't trust 3ed party links.
