### ISSUE TITLE
Accessibility regression: Orca no longer able to read any text

### ISSUE THREAD

**Issue by MarcoZehe** [mate-desktop/mate-terminal#382]
#### Expected behaviour

Orca should be able to read all text in the terminal output in flat review mode.

#### Actual behaviour

Orca only sees the menu bar items and a control named "tab list". Even though it speaks the output normally, reviewing it with flat review does not work.

#### Steps to reproduce the behaviour

1. Turn on screen reader.
2. Open a terminal window.
3. Press the SayLine command, on a laptop this is CapsLock+I, to read the current line.
4. Orca will speak the menu bar. It *should* speak the prompt of the terminal where the cursor is.
5. Try to explore the window with CapsLock+U (line up) or CapsLock+O (line down). Sorry, have no desktop keyboard, so don't know the keys that are used on the desktop/number pad.

#### MATE general version

1.24.1

#### Package version

1.24.1

#### Linux Distribution

Ubuntu Mate 21.04 daily, "Hirsute Hippo"

#### Link to bugreport of your Distribution (requirement)
https://bugs.launchpad.net/ubuntu-mate/+bug/1920985

**Comment by MarcoZehe** [comment]
More info: This works fine in ubuntu MATE 20.10.

**Comment by raveit65** [comment]
@cwendling @alexarnaud ^^^^^
vte problem ???

**Comment by alexarnaud** [comment]
@raveit65 Thanks for pinging us.

It is a known issue:
https://mail.gnome.org/archives/orca-list/2020-December/msg00022.html

This is not related to Mate Terminal nor VTE but to GTK and Orca.

@MarcoZehe The issue should be fixed in Orca 40 release (Or in Ubuntu 21.04). In the meantime, the workaround is to open two tabs or to upgrade to Orca master (the equivalent to NVDA snapshot).

Have a nice day.

**Comment by MarcoZehe** [comment]
Thank you so much, @alexarnaud ! I will do that. Note that the current daily builds of 21.04 still use Orca 3.38, and even upgrading packages doesn't give users anything newer than that. So this better be checked thoroughly before release, since Ubuntu won't include GNOME 40 in 21.04 yet. Closing this issue and the corresponding LaunchPad one as well.
