### ISSUE TITLE
Feature Request: suggests commands as I type based on history and completions.

### ISSUE THREAD

**Issue by wo02ie** [mate-desktop/mate-terminal#406]
![68747470733a2f2f61736369696e656d612e6f72672f612f33373339302e706e67](https://user-images.githubusercontent.com/74661756/146128418-695b1adc-8bd6-4dd0-986a-a351ce522d52.png)

**Comment by lukefromdc** [comment]
Mate-terminal is just a wrapper around VTE, which handles all the stuff taking place 
within the terminal. We don't control the presence or absence of that sort of feature 
as a result

**Comment by mbkma** [comment]
you can launch https://fishshell.com/ in MATE-Terminal. I doubt that we will add support for this, when a good solution like fish exists.
