### ISSUE TITLE
Wrong context menu font is displayed when using vte-0.66.x

### ISSUE THREAD

**Issue by grover92000** [mate-desktop/mate-terminal#407]
#### Expected behaviour
Font should display as expected.

#### Actual behaviour
A monospace font is displayed instead.

#### Steps to reproduce the behaviour
Update to vte-0.66.x. Tested with 0.66.0 and 0.66.2.
Revert back to vte-0.64.2 and all is fine again.

#### MATE general version
1.26

#### Package version
1.26.0

#### Linux Distribution
I build my own from source.

#### Link to bugreport of your Distribution (requirement)
NA

**Comment by N0rbert** [comment]
I can confirm this issue on Ubuntu MATE 22.04 LTS. It is shown on the right:

![21-10_22-04](https://user-images.githubusercontent.com/309456/146995580-5ade871e-442f-44a7-89aa-45fa0b918d4b.png)

I have reported the bug downstream at https://pad.lv/1955505

**Comment by grover92000** [comment]
I've fixed the the issue with the following patch:

[mate-terminal-1.26.0-fix_context_menu_font.patch.txt](https://github.com/mate-desktop/mate-terminal/files/8051811/mate-terminal-1.26.0-fix_context_menu_font.patch.txt)

**Comment by nefigtut** [comment]
> merged into mate-desktop:master

that's all folks!
