### ISSUE TITLE
Mate-terminal 1.26.0 no longer does -t and -x options

### ISSUE THREAD

**Issue by llr51** [mate-desktop/mate-terminal#416]
#### Expected behaviour
Work like 1.24.0 did

#### Actual behaviour
no title and no execute from -t and -x

#### Steps to reproduce the behaviour
execute t9 

I have scripts that open remote terminal to open ssh connections.
They just disappear. (password is not given in the scripts below)
if  execute without the -x t1x to EOL a window opens.

user@VM4:~> cat bin/t9
sleep 1 ; nohup mate-terminal --geometry 80x15 -t llr1 -x t1x llr1 &
sleep 1 ; nohup mate-terminal --geometry 80x15 -t llr4 -x t1x llr4 &
sleep 1 ; nohup mate-terminal --geometry 80x15 -t llr7 -x t1x llr7 &
sleep 1 ; nohup mate-terminal --geometry 80x15 -t llr2 -x t1x llr2 &
sleep 1 ; nohup mate-terminal --geometry 80x15 -t llr5 -x t1x llr5 &
sleep 1 ; nohup mate-terminal --geometry 80x15 -t llr22 -x t1x llr22 &
sleep 1 ; nohup mate-terminal --geometry 80x15 -t llr3 -x t1x llr3 &
sleep 1 ; nohup mate-terminal --geometry 80x15 -t llr6 -x t1x llr6 &
sleep 1 ; nohup mate-terminal --geometry 80x15 -t vm4 -x t1x vm4 &

user@VM4:~> cat bin/t1x
sshpass -p xxxxxxx ssh -l root $1 
date
echo `grep $1 /home/user/bin/t9 | cut -c 11-`
bash 
user@VM4:~>

#### MATE general version
1.26.0

#### Package version
Leap 15.4

#### Linux Distribution
OpenSUSE

#### Link to bugreport of your Distribution (requirement)
Bug 1200358 - Mate-terminal options -x --execute no longer work in 15.4

**Comment by mbkma** [comment]
in Ubuntu MATE 22.04 (MATE version 1.26.0) the -x version works as expected. I performed a quick test with the command `mate-terminal -x sleep 3`.

**Comment by llr51** [comment]
Please close - the -x failed due to change in $PATH default in OpenSUSE. also there was no need for nohup or the & at the end of the line

**Comment by mbkma** [comment]
okay :+1:
