### ISSUE TITLE
Window title setting dialog - enter key not working

### ISSUE THREAD

**Issue by wb027** [mate-desktop/mate-terminal#421]
#### Expected behaviour
Previously, I used version 1.24.0 from Linux Mint 20 Ulyana repository. After entering the title of the window, you could simply press enter.

#### Actual behaviour
Now I have Linux 21 Vanessa and mate-terminal version 1.26.0. Simply pressing enter doesn't work anymore. Now I need to click on the OK button with the mouse, or first press the tab twice and then enter.

#### Package version
$ apt policy mate-terminal
mate-terminal:
  Installed: 1.26.0+mint1+vanessa
  Candidate: 1.26.0+mint1+vanessa
  Version table:
 *** 1.26.0+mint1+vanessa 700
        700 http://mirror.yandex.ru/linuxmint-packages vanessa/upstream amd64 Packages
        100 /var/lib/dpkg/status
     1.26.0-1ubuntu2 500
        500 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages

P.S. I tried the version from the ubuntu repository http://archive.ubuntu.com/ubuntu jammy. The behavior is the same.

**Comment by lukefromdc** [comment]
I have seen this in non-MATE software too-even QT programs with the GTK-2 based theme in use.Not sure where it's coming from but I know we didn't deliberately change anything in MATE to cause this.

**Comment by cwendling** [comment]
This has already been fixed by #394, and it's in 1.27
