### ISSUE TITLE
"Edit -> Keyboard Shortcuts...": List `Ctrl+Delete`, and `Alt+Backspace`/`Alt+Ctrl+h`

### ISSUE THREAD

**Issue by davidhedlund** [mate-desktop/mate-terminal#460]
~~Implement a new text editing shortcut in mate-terminal where Shift+Delete deletes all text from the cursor position to the previous whitespace (moving left).~~

* Ctrl+Delete: to delete text from the cursor position to the next whitespace on the right.
* Alt+Backspace/Alt+Ctrl+h: to delete text from the cursor position to the next whitespace on the right.

I cannot find them:

![image](https://github.com/user-attachments/assets/41463667-ecef-4f06-8426-92c4237e1a63)

**Comment by cwendling** [comment]
Use Bash's `bind` for [`backward-kill-word`](https://www.gnu.org/software/bash/manual/html_node/Commands-For-Killing.html), or whatever similar feature your shell has.  By default you can use <kbd>Alt+Backspace</kbd> or <kbd>Alt+Ctrl+h</kdb>.

Again, I don't think it should be much specific to the terminal app in use, it's the shell editing the command, and it's already fancy.

**Comment by davidhedlund** [comment]
> By default you can use Alt+Backspace or Alt+Ctrl+h.

Thank you very much.

**Comment by davidhedlund** [comment]
@cwendling I changed the topic and updated the top post.

**Comment by cwendling** [comment]
@davidhedlund I still don't think this is a MATE-Terminal issue.  We don't display and allow changing all Bash bindgins (just think of <kbd>Ctrl+A</kbd>, <kbd>Ctrl+E</kbd>, <kbd>Alt+D</kbd>, etc.), it's a property of the *shell*, not the terminal app.

Sure, it *could* send the shell commands to set up bindings, but that would need to know the shell's details (not all shells behave the same in this regards), and I ultimately don't think the terminal app should deal with this.  Again, IMO you should configure your shell the way you like using the *shell's* facilities for this.

**Comment by davidhedlund** [comment]
Ctrl+DEL
```
~$ bind -P | grep ^"delete-char "
delete-char can be found on "\C-d", "\e[3~".
```

# backward-kill-word
Alt+Ctrl+h
```
bind -P | grep ^"backward-kill-word "
backward-kill-word can be found on "\e\C-h", "\e\C-?".
```

Alt+Backspace is not listed, but I will report it to the bind developers.

**Comment by davidhedlund** [comment]
Wouldn't it be useful to inform that shell keyboard shortcuts are not listed to a FAQ or something for MATE Terminal?
