### ISSUE TITLE
Unicode code point entry does not function with code point hex value including 'F'

### ISSUE THREAD

**Issue by dhasenan** [mate-desktop/mate-terminal#5]
You can enter a character by unicode code point hex value; for instance, to insert ☃ ('SNOWMAN'), you can hold down `Ctrl+Shift` and type `U2603`. This works.

When attempting to enter ø 'LATIN SMALL LETTER O WITH STROKE', I need to enter its code point value of F8. I hold down `Ctrl+Shift`, hit `U`, hit `F`...and the 'Find' dialog pops up. I can't actually enter the value.

Tested with MATE Terminal 2.32.0.

**Comment by monsta** [comment]
> As a workaround, you can stop holding CTRL and SHIFT once you've inputted the U and then proceed to type the F and 8 without CTRL and SHIFT down.

I confirm this. But then there's the question: do we really need to do anything about it, when it's enough to press ```Ctrl-Shift-U``` once and no need to hold ```Ctrl-Shift``` after that?

**Comment by dhasenan** [comment]
No, it's fine as is.
