### ISSUE TITLE
Strange mouse issue on right half of terminal window using tmux

### ISSUE THREAD

**Issue by thonixx** [mate-desktop/mate-terminal#63]
I have a strange issue which only occurs in tmux and enabled mouse mode. I am testing several configurations in tmux, i.e. mouse mode amongst other options. With mouse mode in tmux you can select a pane or selecting text in tmux copy mode. But clicking in the right half of the mate terminal I end up having typed strange characters. It is complicated to describe so please have a look at this video:

mate-terminal: https://www.youtube.com/watch?v=J0hdXxgv014
gnome-terminal comparison: https://www.youtube.com/watch?v=X60_GdWcRkM

**Comment by egmontkob** [comment]
The legacy mouse protocol only supports coordinates up to 223. The extended version is supported by tmux and newer vte versions, but not by the older gtk2-based vte.

**Comment by monsta** [comment]
Ok, marking it accordingly then.

**Comment by monsta** [comment]
@egmontkob: now that we're GTK+3 only, what should we change to fix this? Or is it auto-fixed now due to new vte used?

**Comment by egmontkob** [comment]
@monsta It is auto-fixed.

**Comment by monsta** [comment]
Ok, thanks, I'm closing this then.

@thonixx: you'll be able to test it when MATE 1.16 is released.
