### ISSUE TITLE
Large blank areas during scrollback

### ISSUE THREAD

**Issue by mothlight** [mate-desktop/mate-terminal#64]
Mate Terminal 1.6.2 on Fedora 20. Scrollback is set to unlimited.

This only seems to happen with commands that make lots of output, something like 'yum update', scrolling back you end up with pages and pages of blank space. So, run the command, it generates a few pages out output. Then try to scrollback through it. About 6 lines past the top of the screen, you have to click the scrollbar through about 20 pages of blank lines before you get to the rest of the output.

Another way to reproduce it, type 'ls' three or four times to fill up a few screens worth then try to scroll backwards through that.
![mateterminalscrollproblem](https://cloud.githubusercontent.com/assets/880286/2979767/46ef4c90-dbd6-11e3-88e9-7449769641d1.png)

**Comment by monsta** [comment]
Not sure if it was in mate-terminal itself or in libvte, but I think it was fixed for good in 1.8 - at least I've never seen it there. If it's not confirmed in 1.10 I'll close it.
