### ISSUE TITLE
Character encoding not applied on new tab terminal

### ISSUE THREAD

**Issue by drJeckyll** [mate-desktop/mate-terminal#65]
Old issue from gnome-terminal. 
Open mate-terminal. Change encoding to windows-1251 for example. Open new tab in same terminal. You can see in encoding menu that encoding is set to windows-1251. Type something in windows-1251 - encoding is wrong. You need to select again already selected in menu encoding to become active.

**Comment by monsta** [comment]
The encoding in new tab seems to be always set to the default value (most probably it's UTF-8).
It's just the menu that was showing the value from the previous tab. In the latest mate-terminal versions the menu in the new tab always shows that the encoding is UTF-8, so the issue is no more.
