### ISSUE TITLE
Terminal does not display telugu characters properly. 

### ISSUE THREAD

**Issue by vra5107** [mate-desktop/mate-terminal#73]
I am trying mate for the first time and I was really looking for Terminal support for Indic languages. 

Terminal does not display telugu characters well. I tried installing various telugu fonts but nothing seems to work. The conjuncts are displayed as separate characters an the characters overlap. You can see the text displayed properly in the line below. 

`సంపూర్తియైన, సంపూర్ణమైన, నెరవేరిన, ముగిసిన`

KDE terminal seems to have a problem with cursor movement. Cursor movement for indic languages should be between syllables. I am just mentioning this because this seems to be a common error on other platforms as well.

FWIW, I would spend time to fix this issue if I knew C / CPP, I already contribute to opensource. Learning CPP just to fix this is a steep requirement and would take a considerable effort on my part. So your help with this issue is greatly appreciated. 

![selection_001](https://cloud.githubusercontent.com/assets/122128/4554181/cff43952-4ea8-11e4-86de-6e1b50f4760b.png)
##

**Comment by raveit65** [comment]
Where did you see the commits at git gnome?

**Comment by monsta** [comment]
I don't think it has been accepted into VTE... searching commit log for indic/indian/telugu gives me nothing. Anyway, even if it will ever be accepted there, only GTK+3 build of mate-terminal will benefit from it.

**Comment by Shreeshrii** [comment]
Has there been any update on this. I am also looking for a terminal which supports Indic/Devanagari.

**Comment by monsta** [comment]
As it should be done in VTE, I'm closing this. Not fixable at our side.

**Comment by esdnm** [comment]
> Has there been any update on this. I am also looking for a terminal which supports Indic/Devanagari.

I have found that KDE's terminial app support Bangla pretty well.
