### ISSUE TITLE
-e command line parameter does not work

### ISSUE THREAD

**Issue by SukkoPera** [mate-desktop/mate-terminal#83]
mate-terminal releases from 1.9.0 (can't really speak for earlier versions, I began using it with this version) report through `mate-terminal --help-terminal-options`:

>  -e, --command                   Execute the argument to this option inside the terminal

But actually `-e` doesn't work for this purpose, rather `-x` does, which is the option that was used in gnome-terminal.

The following forum post deals about the issue: http://forums.mate-desktop.org/viewtopic.php?f=16&t=3362

**Comment by NiceandGently** [comment]
try 1.9.1, here in fedora rawhide (f22) the -e option works, ie, mate-terminal -e 'caja --no-desktop'

**Comment by monsta** [comment]
Both ```-e``` and ```-x``` work fine for me in 1.10.1 (when launched via Alt-F2 dialog).

**Comment by SukkoPera** [comment]
I can confirm that. Unfortunately my Code::Blocks build just decided to break, so I can't test in there, but I can't see any reason why it shouldn't work.

Feel free to close.

**Comment by monsta** [comment]
I think you can close it yourself as you're the reporter :smile:
