### ISSUE TITLE
No mention about GNOME terminal in the About dialog

### ISSUE THREAD

**Issue by llbit** [mate-desktop/mate-terminal#84]
Hi, I wonder why MATE Terminal does not mention that it is a fork of GNOME Terminal in the About dialog? That seems like a good thing to include in there.

**Comment by raveit65** [comment]
Well, we do not mention in about-dialogs from our applications that we forked the gnome2 desktop.
As you can see all copyrights infos from gnome are there in about-dialog.
```
Copyright © 2002–2004 Havoc Pennington
Copyright © 2003–2004, 2007 Mariano Suárez-Alvarez
Copyright © 2006 Guilherme de S. Pastore
Copyright © 2007–2010 Christian Persch
```
