### ISSUE TITLE
Improve auto-complete and/or tab completion feature

### ISSUE THREAD

**Issue by tranjeeshan** [mate-desktop/mate-terminal#91]
mate-terminal needs to improve its' auto-complete and/or tab-completion feature. That way, mate-terminal would be proved to be more user-friendly for newbies. And it'd be handy, too!

**Comment by infirit** [comment]
autocomplete is not a feature of the terminal emulator but of the shell running inside it. You will want to ask your distro of choice to either how to install or to improve them.
