### ISSUE TITLE
mate-terminal --title=foo option does not work.

### ISSUE THREAD

**Issue by greearb** [mate-desktop/mate-terminal#93]
mate-terminal --title=foo silently fails to set the title to foo.

See fedora bug:  https://bugzilla.redhat.com/show_bug.cgi?id=1254805

**Comment by infirit** [comment]
Works for me when I set the profile to __not__ update the title when the shell/shell programs set it.

**Comment by greearb** [comment]
Can you add some detail on how you configured the profile?

At the least, it should be mentioned in the man page next
to the --title option.

And probably, --title should automatically disable setting
the title from a shell program.

Thanks,
Ben


On 08/18/2015 05:08 PM, Sander Sweers wrote:
> Works for me when I set the profile to *not* update the title when the shell/shell programs set it.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/mate-desktop/mate-terminal/issues/93#issuecomment-132396930>.
>

-- 
Ben Greear <greearb@candelatech.com>
Candela Technologies Inc  http://www.candelatech.com

**Comment by infirit** [comment]
>Can you add some detail on how you configured the profile? 

edit -> profile preference -> second tab

>At the least, it should be mentioned in the man page next to the --title option

Patches welcome.

>And probably, --title should automatically disable setting

I really do not see why, just because some people are confused about how applications set the terminal title? Instead I suggest folks create a profile that has this options set the way you need  ut and start ``mate-terminal`` with ``--profile``.

**Comment by NiceandGently** [comment]
@greearb 
in edit -> profile preference -> second tab there is a drop-down-menu under title, change here to 'keep intial title'.
Than the -t option works.

**Comment by greearb** [comment]
On 08/19/2015 04:52 AM, Sander Sweers wrote:
>     Can you add some detail on how you configured the profile?
>
> edit -> profile preference -> second tab

Thanks, I will try this.

>
>     At the least, it should be mentioned in the man page next to the --title option
>
> Patches welcome.

I have my own projects to patch...surely someone that already has
a build environment for this project could do it more efficiently
than I can.

>
>     And probably, --title should automatically disable setting
>
> I really do not see why, just because some people are confused about how applications set the terminal title? Instead I suggest folks create a profile that has
> this options set the way you need ut and start |mate-terminal| with |--profile|.

Because what possible reason would someone have to use --title=foo and then not
want the title to actually be foo?

And for what it's worth, I used several of the options I found searching to try
setting terminal title using funny escape characters in a bash shell.  One of them
actually did change the title of the terminal, but the title did not change in the
bottom task-bar.  There may be more bugs related to setting titles....

Thanks,
Ben


-- 
Ben Greear <greearb@candelatech.com>
Candela Technologies Inc  http://www.candelatech.com

**Comment by raveit65** [comment]
@greearb 
Could you handle this configuration?
Can we close this issue?

**Comment by greearb** [comment]
You can close it..I think it was fixed for next upstream
release, and I have a work-around for now.

THanks,
Ben


On 11/28/2015 11:23 AM, Wolfgang Ulbrich wrote:
> @greearb <https://github.com/greearb>
> Could you handle this configuration?
> Can we close this issue?
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/mate-desktop/mate-terminal/issues/93#issuecomment-160330431>.
>

-- 
Ben Greear <greearb@candelatech.com>
Candela Technologies Inc  http://www.candelatech.com
