### ISSUE TITLE
--tab Doesn't Work

### ISSUE THREAD

**Issue by machineghost** [mate-desktop/mate-terminal#96]
I recently updated my Linux distro (Linux Mint), and got the latest(?) version of mate-terminal, version 1.10.0.  However, I discovered a bug in it.

When I run `mate-terminal --tab` from inside a mate-terminal, it *should* open up a new tab in the existing terminal:

>       --tab  Open a new tab in the last-opened window with the  default  pro‐
>              file

However, it doesn't; instead it opens up an entirely new instance of mate-terminal (ie. a new window).

**Comment by raveit65** [comment]
confirmed in fedora 22,
--tab does the same as --window.
As a workaround until it is fix you can use 'crtl+shift+t' which is much faster ;)

**Comment by flexiondotorg** [comment]
I submitted a patch for this ages ago. Perhaps it never made master, just 1.8?

**Comment by machineghost** [comment]
> As a workaround until it is fixed you can use 'crtl+shift+t' which is much faster ;)

That's a great workaround if you are manually starting the tab.  However, if you're trying to write a script which programmaticlly starts several tabs at once (eg. to start a bunch of servers) then you're stuck with a script that generates a ton of open windows.

**Comment by raveit65** [comment]
Indeed the commit is in master https://github.com/mate-desktop/mate-terminal/commit/71204c2d
which closed 
https://github.com/mate-desktop/mate-terminal/issues/45

**Comment by monsta** [comment]
It's weird but I confirm it's broken in 1.10 while it works in 1.8.1...

**Comment by raveit65** [comment]
ok, the regression was included somewhere between 1.9.0 and 1.9.1 release

**Comment by monsta** [comment]
Ok, ```git bisect``` told me that https://github.com/mate-desktop/mate-terminal/commit/bf0b2dfe547da493e016dde213a8454e6831eb86 is the commit that broke it.

**Comment by raveit65** [comment]
@machineghost 
If you can't rebuild mate-terminal for yourself please open a report in linuxmint and ask for addind the fix there.

**Comment by machineghost** [comment]
@raveit65 I *could* rebuild mate-terminal, but years of using Linux have given me a healthy fear of straying away from the safety of package management :)  I will file a Linux Mint ticket though.

Thanks so much for the quick response!

**Comment by monsta** [comment]
This might help you with patching and rebuilding .deb packages:

https://raphaelhertzog.com/2010/12/15/howto-to-rebuild-debian-packages/
https://raphaelhertzog.com/2011/07/04/how-to-prepare-patches-for-debian-packages/

**Comment by dancingfrog** [comment]
@machineghost Can you post a link to your bug report so we can follow it?

**Comment by machineghost** [comment]
Sure thing.  When I went to file mine previously I found a similar ticket already existed, so I didn't actually file my own.  However, when I went back to find that ticket (so I could link it here) I wasn't able to, so I just wound up filling a new ticket:
https://bugs.launchpad.net/linuxmint/+bug/1505379
