### ISSUE TITLE
allow to map shortcut Ctrl-Tab to switch tabs

### ISSUE THREAD

**Issue by kenden** [mate-desktop/mate-terminal#98]
Currently the key Tab is reserved by Gnome and cannot be used as a custom shortcut.
Maybe, as mate-terminal is not an official Gnome project, it is possible to work around this?

See this page for reference to:
- the gnome-terminal bug: https://bugzilla.gnome.org/show_bug.cgi?id=123994
- the discussion that goes with it: https://mail.gnome.org/archives/desktop-devel-list/2009-November/msg00220.html
##

**Comment by monsta** [comment]
I see Firefox has that and ctrl-shift-tab for switching tabs, so unless we'll find some actual limitation, we might implement it in mate-terminal as well.

**Comment by bl0ckeduser** [comment]
The functionality is already there, you can use ctrl-pageup/ctrl-pagedown to cycle between tabs. it should be trivial to change it to ctrl-tab

**Comment by kenden** [comment]
Ctrl-pageup requires 2 hands, ctrl-tab is pretty standard to switch tabs.

**Comment by raveit65** [comment]
Another shortcut is alt+1, alt+2, etc for switching tabs.

**Comment by eshepelyuk** [comment]
How to enable this feature ? Using Ubuntu 18.04 and Mate 1.20 - I can't set Ctrl+Tab from keybinding screen

**Comment by alexarnaud** [comment]
@eshepelyuk are you talking of the keyboard shortcut screen of mate Terminal ?

**Comment by eshepelyuk** [comment]
yes

**Comment by monsta** [comment]
Currently there's no option in GUI. You can use `dconf-editor` or `gsettings` command-line tool.

```
$ gsettings get org.mate.terminal.global ctrl-tab-switch-tabs
true
```
